### ISSUE TITLE
Détection automatique du type de Demande pour une ordonnance numérique

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#100]
Ajout d'une fonction dans l'extension qui inspecte le contenu d'une demande et détecte certains mots clefs pour sélectionner automatiquement le type de l'ordonnance numérique.

Actuellement, le type d'ordonnance numérique est automatiquement mis sur Biologie.

Selon la présence de certains mots clefs dans le texte de l'ordonnance, changer automatiquement pour:
- Kinésithérapie si présence des mots clefs: "kiné", "kinésithérapie", "réeducation", "MKDE", "kinésithérapeute"
- Infirmier si présence des mots clefs: "IDE", "infirmier(s)", "pansement(s) ?"
- Pédicure si présence des mots clefs: "podologie", "podologique", "pédicure"

**Comment by DrFloW71** [comment]
Super idée!!

**Comment by Refhi** [comment]
C'est fun et ça fonctionne très bien !
Validé et intégré à la 2.4
