### ISSUE TITLE
Ajout d'une cotation par défaut selon le mode de la FSE

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#101]
Actuellement, la cotation par défaut est toujours celle appelée "Défaut"

- Ajout d'une option pour permettre à l'utilisateur de spécifier manuellement le nom de sa cotation par défaut (ex: GS)
- Ajout d'une option pour permettre à l'utilisateur de spécifier manuellement le nom de sa cotation par défaut selon le mode de la FSE (ex: TCG pour le mode Sesam sans vitale, GS pour le mode sécurisé)

**Comment by DrFloW71** [comment]
Pour les secteur 2: si ALD est cochée pour mettre la cotation par défaut au TO

**Comment by DrFloW71** [comment]
Oui c'est le tarif opposable. En gros si la case ALD est cochée pouvoir mettre une cotation spécifique par défaut.

**Comment by Refhi** [comment]
cf. #102
