### ISSUE TITLE
Détection automatique de l'âge du patient lors de la réalisation d'une FSE

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#102]
En lien avec #101
Ajout d'une détection de l'âge du patient pour soit:
- Ajouter automatiquement une cotation MEG à la cotation par défaut si < 6 ans
- Afficher un message d'alerte si MEG n'est pas utilisée alors que patient est < 6 ans

**Comment by DrFloW71** [comment]
Comme vous êtes chauds (mais pas sur que ça soit possible): alerte si le mot clé ECG est présent dans l'observation et l'ECG n'est pas côté! Pareil pour MMSE, MADRS...

**Comment by Abeldvlpr** [comment]
C'est envisageable mais ca demande un peu plus de travail

**Comment by Refhi** [comment]
> Comme vous êtes chauds (mais pas sur que ça soit possible): alerte si le mot clé ECG est présent dans l'observation et l'ECG n'est pas côté! Pareil pour MMSE, MADRS...

Effectivement c'est possible, mais pour l'instant je préfère qu'on se concentre sur des solutions simples et solides (l'analyse systématique de toutes les entrées de consultation avec regex + entrée en mémoire + surveillance du nom du patient. etc = bcp de développement pour un résultat qui me parait trop hasardeux, désolé)

Cela dit, j'ai préparé le terrain pour que ça soit plus simple à coder dans un second temps, donc peut-être relance-nous quand tu verras que le suivi des tickets commence à fondre :)

Sinon fait dans #170
