### ISSUE TITLE
Décocher automatiquement le texte et IHE_XDM.zip dans les échanges sécurisés

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#108]

**Comment by Refhi** [comment]
celui-là je ne peux pas le tester, j'attends ton feu vert pour le considérer comme fiable et bien intégré à l'alpha ?
Dès que c'est fait je ferme le ticket :)

**Comment by Abeldvlpr** [comment]
Pas de soucis particuliers sur mes tests
