### ISSUE TITLE
Améliorer la saisie des antécédents

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#112]
Simplifier le panneau de la CIM-10 en retirant les sous catégories (ex: Spondylarthrite ankylosante - Région lombaire, - Région sacrée etc.) et en n'affichant au premier rang que les catégories principales

**Comment by DrFloW71** [comment]
Trop bonne idée tant la CIM est inutilisable !

**Comment by Refhi** [comment]
![image](https://github.com/user-attachments/assets/03dfea7f-e35d-4385-802f-bf1779a3819e)
![image](https://github.com/user-attachments/assets/5a6ca730-c023-41bc-ac22-e14c0320d154)
![image](https://github.com/user-attachments/assets/7c7d74c0-5406-4cd6-b377-869a80843ad4)

Encore quelques bugs à résoudre mais ça avance bien
