### ISSUE TITLE
DMP Type de document

### ISSUE THREAD

**Issue by DocTigs** [Refhi/Weda-Helper#116]
Bonjour,

Il y a quelques mois, j'avais demandé à ce que dans l'interface courrier, le type de document "CR de consultation", "lettre de liaison" soit prédéfini. Ce que vous avez fait, avec le système qui garde en mémoire le dernier type de document utilisé est top, encore merci.

Serait il possible de faire la même chose, lorsque depuis le dossier patient, on veut mettre un pdf dans le DMP. Si on clique sur le bouton DMP, une interface s'ouvre, avec toujours un préchoix positionné sur "Lettre de liaison à la sortie d'un établissement". Est-ce que ce pré choix pourrait retenir le dernier choix effectué ?

![Capture d'écran 2024-05-30 093249](https://github.com/Refhi/Weda-Helper/assets/162317219/3b0f3e52-f8ec-4e0c-ac78-f8af8e68e6dd)

Merci !

**Comment by Refhi** [comment]
Bonjour, ça a l'air accessible :)

On creuse ça quand on a le temps

**Comment by Refhi** [comment]
Après étude du problème quelques considérations : 
- lorsque l'on envoie un ordo ou un certificat, Weda va automatiquement sélectionner une catégorie correspondante. Là ce message s'affiche lorsque tu essaies d'envoyer un courrier, c'est bien ça ?
- y a-t-il d'autres documents que tu souhaites envoyer et qui posent problème ?

SI j'analyse bien ta demande il faudrait que : 
- lorsque ce panneau s'affiche avec "Lettre de liaison à la sortie d'un établissement de soins" et que tu sélectionnes une autre catégorie, il l'enregistre.
- lorsque ce même panneau s'affiche avec "Lettre de liaison à la sortie d'un établissement de soins" affiché => il sélectionne automatiquement la catégorie précédemment enregistrée. (ça devrait normalement faire ça que pour les courriers du coup).

Est-ce que tu me confirmes que ça répondrait à ta problématique ?

**Comment by Refhi** [comment]
@DocTigs ?
