### ISSUE TITLE
[2.3] Ajout des unités sur les constantes ne fonctionne pas

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#121]
Je regarde ca ce soir en rentrant du cabinet

**Comment by Refhi** [comment]
https://github.com/Refhi/Weda-Helper/commit/67ab6778f84fdcf2e68cb21987e3270253a9fe18

+ retrait des valeurs par défaut en dur dans le code au profit de la liste présente dans background.js
