### ISSUE TITLE
Permettre des raccourcis claviers de 1, 2 et 3 combinasons 

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#124]
permettrait par exemple de faire 
Ctrl+P pour imprimer
et Ctrl+Maj+P pour télécharger, ou encore
F1 pour ouvrir une nouvelle consultation

**Comment by Abeldvlpr** [comment]
Pour l'instant, l'implémentation pour le choix du raccourcis dans les options s'arrête à n'importe quelle combinaison de 2 touches. Ce qui me semble le mieux c'est de faire:
- Autoriser 1 touche si c'est F1, F2, etc...
- Autoriser 2 à 3 touches avec obligatoirement une des touches qui est une lettre ou un chiffre

Si ca te va comme implémentation je m'en occupe
