### ISSUE TITLE
Vérifier que tout les pushdown soient bien passés sur la nouvelle bibliothèque

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#125]
Il y a notamment les pushdown dans fse.js et +
- Il serait probablement pertinent de les passer par le nouveau système hotkeys.js ?
@Abeldvlpr un avis sur le sujet ?

**Comment by Abeldvlpr** [comment]
De ce que je vois, il y'a surtout dans `fse.js` qui mériterait de passer en pushDown les autres raccourcis que je trouve dans le code sont:
- Le Alt pour afficher l'aide aux raccourcis Wmenu dans `content.js`
- Les raccourcis de prescription de posologie dans `prescription.js`
- Les raccourcis Enter et Tab dans `searchUpload.js`

Est-ce que tu penses que ca nécessite de les passer dans hotkeys sachant qu'ils sont tous en une touche ?
Je peux comprendre l'itnérêt de tout avoir sur la même librairie. Je te laisse me dire ce que tu en penses et si besoin je peux m'occuper de l'implémentation.

**Comment by Refhi** [comment]
Mmmm... en effet, ça fonctionne tel quel, pour l'instant pas trop d'intérêt à pousser le vice jusqu'au bout.
