### ISSUE TITLE
Raccourcis clavier defectueux quand dans des iframes.

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#127]
par exemple Ctrl+P déclenche l'impression classique au lieu d'écouter le pushdown et de lancer la procédure attendue

Essai : 
- windows 10
- chrome
- focus dans le champ de texte de https://secure.weda.fr/FolderMedical/CourrierForm.aspx

fonctionnement ok si hors champ de texte

**Comment by Abeldvlpr** [comment]
Je regarde en détail ce soir, ca semble venir spécifiquement de l'éditeur de courrier, soit car c'est une iframe soit parcequ'il vole les événements keydown et ne les propage pas..

**Comment by Refhi** [comment]
Effectivement ça semble être exclusivement quand on est dans un iframe (sous réserve)

**Comment by Refhi** [comment]
J'ai peut-être une piste peut-être un peu plus directe, en ajoutant une condition à la partie intégrant hotkeys.js dans keyCommands, en gros quelque chose comme ça : 

```
function addHotkeyToDocument(doc, shortcut, action) {
    if (shortcut != undefined)
        hotkeys(shortcut, { scope: doc }, function (event, handler) {
            event.preventDefault();
            action();
        });
}
```
ça permettrait de définir plus facilement le champ d'application du shortcut : document dans un premier temps, puis iframe dès qu'on en détecte une. Peut-être via lightObserver ?
J'essaie d'avancer dessus tout à l'heure si ça te va

**Comment by Refhi** [comment]
```
// // Gestion des raccourcis claviers via hotkeys.js
// Pour ajouter les raccourcis sur un élément spécifique
function addHotkeyToDocument(scope, element, shortcut, action) {
    if (shortcut != undefined)
        console.log('Ajout du raccourci', shortcut, 'avec la fonction', action, 'dans le scope', scope);
        hotkeys(shortcut, { scope: scope, element: element }, function (event, handler) {
            event.preventDefault();

            action();
        });
}

chrome.storage.local.get(["defaultShortcuts", "shortcuts"], function(result) {
    hotkeys.filter = function(event){
        return true; // Permet d'utiliser les raccourcis depuis un input ou un textarea
    }
    const entries = Object.entries(keyCommands);
    for (const [key, action] of entries) {
        var shortcut;
        if (result.shortcuts == undefined) {
            shortcut = result.defaultShortcuts[key]["default"];
        }
        else if (result.shortcuts[key] == undefined) {
            shortcut = result.defaultShortcuts[key]["default"];
        }
        else {
            shortcut = result.shortcuts[key];
        }
        addHotkeyToDocument("all", document, shortcut, action);
        lightObserver('iframe', function (newElements) {
            for (const [key, action] of entries) {
                addHotkeyToDocument("iframes", newElements[0].contentDocument, shortcut, action);
            }
        }, document, true);
    }
});
```
Bon ça avance, faut encore affiner le lightObserver, mais ça a l'air d'être la bonne direction je pense

**Comment by Refhi** [comment]
:)

J'ai fait quelques commitq depuis pour faciliter la lisibilité et l'usage, n'hésite pas à me tenir au courant (j'espère rebosser dessus ce soir)

**Comment by Refhi** [comment]
Bon.
Avec
```
iframe.contentDocument.addEventListener('keydown', function(event) {
                console.log('Touche pressée:', event.key);
            });
```
j'arrive à afficher un log

```
            addShortcuts(keyCommands, iframe.contentDocument, 'iframe' + (index + 1));
``
mais hotkeys.js n'y arrive pas alors qu'il semble que je sélectionne le bon element cible ??

**Comment by Refhi** [comment]
bon apparemment c'est en ligne 359 dans hotkey.js que se pose le problème...

**Comment by Refhi** [comment]
semblerait que je ne déclare pas le scope correctement... on est pas loin de la solution...

**Comment by Refhi** [comment]
Ah ! Enfin : 
https://github.com/Refhi/Weda-Helper/commit/0bbf9dc8efe9e3b61b245ce4bf2bf9c446725967

En pratique multiples problèmes cumulés : 
- le "scope" n'était pas correctement écouté dans hotkey.js => bypass mis en place
- on peut mettre les raccourcis directement dans les iframes, mais si celles-ci sont rechargées (par exemple lors du chargement des atcds) => on perd les raccourcis. Pour l'instant j'ai mis un bête timer à 1 seconde, mais dans l'idée il faudrait faire quelque chose de plus propre, peut-être en mettant un lightObserver sur l'apparition des iframes.

**Comment by Abeldvlpr** [comment]
Tu changeais le scope avec `setScope()` ?

**Comment by Refhi** [comment]
Ok !

J'ai récupéré des bouts de code dans ton commits, fait des recherches de mon côté, et cherché comment implémenter de façon fiable et reproductible les raccourcis dans les pages...

Au final je passe pas par ton PR (on a pris des méthodes un peu tangentes), mais merci pour tes propositions :) J'en ai repris une partie

Du coup par esprit de simplicité j'ai pour l'instant complètement désactivé le système de scope, ça évite de rajouter un eventManager pour surveiller le focus.

J'ai également fait une nouvelle fonction qui risque d'être utile à l'avenir :+1: 
``` 
// // Sorte de post-chargement pour les pages, car le onload fonctionne mal, et après une mutation c'est pas toujours évident
function afterMutations(delay, callback) {
    let timeoutId = null;
    const action = () => {
        console.log('Aucune mutation détectée pendant 100ms, je considère la page comme chargée. Rechargement des raccourcis...');
        callback();
    };

    const observer = new MutationObserver((mutationsList, observer) => {
        for(let mutation of mutationsList) {
            // Réinitialise le délai chaque fois qu'une mutation est détectée
            clearTimeout(timeoutId);
            timeoutId = setTimeout(action, delay);
        }
    });

    observer.observe(document, { childList: true, subtree: true });
};
```
L'intérêt c'est de re-charger certains trucs dès qu'on détecte la fin d'une tetrachi** de mutations, ce qui correspond en général à la fin du chargement de la page ou d'un changement notable (genre le chargement de l'historique au sein d'une fenêtre de consultation).
Donc on peut faire des trucs réactifs à 100 (par exemple) ms prêt sans surcharger le script !
J'imagine que ça sera aussi utile pour #131
