### ISSUE TITLE
Changer de champs de texte via tabulation dans les consultations

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#131]
Souvent pénible de devoir sauter d'un champ de texte à l'autre avec la souris.
J'aimerais bien pouvoir utiliser tab et maj+tab pour passer de l'un à l'autre, comme si on utilisait un taborder.

**Comment by OlivierSoussain** [comment]
Je suis tout à fait d'accort. 
Quand on ouvre une conusultation l'idéal serait de mettre le focus sur le titre. 
Puis de pouvoir naviguer avec la tabulation dans la différente fenêtre ( qui sont chez moi histoire de la maladie, examen clinique, paraclinique et conclusion )

**Comment by Refhi** [comment]
https://github.com/Refhi/Weda-Helper/tree/tabConsult

**Comment by Refhi** [comment]
@OlivierSoussain pour le focus dans le champ de titre j'ai mis ça en une option désactivée par défaut. Lors de la sortie de la 2.5 je t'inviterais à l'activer pour avoir ce point
