### ISSUE TITLE
Détecter automatiquement le companion

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#136]
Peut-être une fenêtre automatique à l'ouverture du logiciel ?
=> "le companion a été détecté, souhaitez-vous activer le TPE/l'impression automatique"

**Comment by Abeldvlpr** [comment]
Excellente idée !

**Comment by Refhi** [comment]
https://github.com/Refhi/Weda-Helper/commit/4929cab9be88a6211eb6ba2055a78f1b30161508
