### ISSUE TITLE
Valider automatiquement une ordonnance numérique de médicaments

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#137]
Ajout d'une option pour valider automatiquement une ordonnance numérique de médicaments si l'option "Cocher automatiquement Oui pour le consentement du patient" est cochée.

**Comment by Abeldvlpr** [comment]
Implémenté dans [4e77538](https://github.com/Refhi/Weda-Helper/commit/4e7753824dc39d85a542d2c9a76a69b37c2c6756)

**Comment by Refhi** [comment]
Je me permet de ré-ouvrir car j'ai l'impression que ça ne fonctionne pas sur les ordos de bio, je regarde tt à l'heure

**Comment by Abeldvlpr** [comment]
J’ai mis volontairement que les ordonnances de médicaments pour l’instant pour laisser le choix du type d’ordonnance pour les demandes (Kine, bio, IDE, etc)…
Si on a suffisamment confiance dans l’option de sélection du type d’ordonnance on peut l’activer sur les deux pages

**Comment by Refhi** [comment]
une proposition : 
- quand c'est activé, ça valide l'ordonnance numérique automatiquement *seulement* si un des termes regex a été trouvé, sinon ça attends la validation du prescripteur ?

**Comment by Abeldvlpr** [comment]
Pas mal comme solution !
Ça demandera juste une validation pour la biologie qui n’a pas de Regex propre

**Comment by Refhi** [comment]
ou sinon on fait comme pour la désactivation de l'ordo numérique pour l'imagerie et on considère que c'est ok si "Laboratoire" est en rouge ?
![image](https://github.com/Refhi/Weda-Helper/assets/2778215/0382ea57-c1a6-489e-b859-3f79e9f4c3b5)

**Comment by Abeldvlpr** [comment]
Ajout des demandes dans fd38cc5

**Comment by Refhi** [comment]
Je teste ça tout à l'heure

**Comment by Refhi** [comment]
J'ai l'impression que ça ne fonctionne pas :-/ pour les bios en tout cas
Je te laisse jeter un oeil ? Sinon je m'en occupe à l'occasion

**Comment by Abeldvlpr** [comment]
> J'ai l'impression que ça ne fonctionne pas :-/ pour les bios en tout cas Je te laisse jeter un oeil ? Sinon je m'en occupe à l'occasion

Si tu peux ré-essayer à l'occasion, j'ai rajouté un délai

**Comment by Refhi** [comment]
Normalement c'est fix grace à #191
