### ISSUE TITLE
Alt+V pour valider un conseil de saisie libre déclenche 2-10 itérations du conseil

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#139]
https://secure.weda.fr/FolderMedical/PrescriptionForm.aspx

**Comment by Refhi** [comment]
Contourné mais en fait un bug de         () => GenericClicker("title", "Valider"),
qui envoie l'instruction plusieurs fois, probablement au DOM change.

**Comment by Refhi** [comment]
Contournement seulement partiellement efficace... (2 itération seulement...) => à creuse

**Comment by Refhi** [comment]
Bon, le diagnostique est probablement que dans certains cas les raccourcis s'implémentent plusieurs fois dans un éléments.
En général ça ne pose pas de problème, mais dans ce cas précis on se retrouvait avec un multiclic assez pénible.
J'ai ajouté une fonction qui surveillance l'absence de clics trop rapide en implémentant une période réfractaire de 200ms pour pas mal de choses, à voir si ça gêne à l'usage ou si d'autres fonctions en ont besoin.

**Comment by Abeldvlpr** [comment]
Le plus simple me semble de rajouter `hotkeys.unbind()` avant chaque ajout d’un raccourci pour s’assurer qu’il ne soit pas en double

**Comment by Refhi** [comment]
Intéressant, je vois cette piste à l'occasion

**Comment by Refhi** [comment]
Le problème est uniquement présent sur les iframes, donc il faudrait trouver une solution pour ne retirer les raccourcis que sur les iframes...
L'avantage de la période refractaire est que ça limite aussi les risques en cas de double clic ou de maintient d'un raccourcis clavier (dans l'exemple ci-dessus, si on maintient un peu trop longtemps alt+v par exemple, on se retrouve avec 40+ itérations...)
Donc pour l'instant je laisse le fix que j'ai mis, qui me parait sécuriser un peu plus l'usage des raccourcis, à voir à l'usage.
