### ISSUE TITLE
Imprimer automatiquement la feuille de soin à faire signer quand on fait un dégradé 

### ISSUE THREAD

**Issue by OlivierSoussain** [Refhi/Weda-Helper#144]
Quand on fait un dégradé il faut généralement faire signer la feuille de soin, on doit donc l'imprimer puis la valider. 
Il serait pertinent d'automatiser cela.

**Comment by Refhi** [comment]
J'ai vu que tu avais fermé le ticket, est-ce volontaire ? L'idée me parait pourtant intéressante à explorer ?

**Comment by OlivierSoussain** [comment]
Oui, on peut la laisser. ( j'ai encore du mal avec le maniement de gitHub. )

**Comment by Abeldvlpr** [comment]
Le SCOR ne résous pas le problème, l’implémentation actuelle de Weda nécessite toujours d’imprimer la feuille, de la faire signer, de la scanner et de la mettre en pièce jointe à la FSE..
Ce qui me semble plus pratique et plus simple c’est de rajouter un icône imprimante dans le dossier patient sur l’affichage de la recette + FSE
On peut lancer l’impression via l’API de VitalZen directement de ce que j’ai vu..
Je vais regarder ça plus en detail

**Comment by Refhi** [comment]
Sérieux ? Ils ont pas automatisé le process de FSE avec le SCOR ?
Bon ben du coup c'est effectivement intéressant qu'on se lance !
Je vois bien un potentiel où ça crée la fse avec notre signature et "ne peut signer" de coché(ou signature via tablette ?), puis ça l'envoie automatiquement via le SCOR 🤔
Par contre VitalZen devrait arriver en fin de vie rapidement à ce que je comprends. Je propose de donc de rester sur une impression via le Companion, ça évitera aussi de multiplier les api ? 🤔

Tant que j'y pense : les tickets sont pour l'instant "le 1er qui a le temps/l'envie" s'en occupe. Si on veut absolument s'occuper d'un ticket on crée une branche dédiée pour se l'approprier ?

**Comment by Abeldvlpr** [comment]
Non... Et de ce que j'ai compris ce n'est pas prévu...
Oui je suis d'accord avec toi c'est plus simple de lancer l'impression via le compagnon. Je parlais de l'API VitalZen pour récupérer le PDF de la FSE dégradée. Il faut regarder comment c'est fichu...

Ca me va pour l'organisation !

**Comment by Abeldvlpr** [comment]
Il est possible de récupérer le PDF d'une feuille de soin en faisant un `POST https://localvz.comunica.fr:10100/feuille/duplicata` avec une payload `billNumber: "000001"}`
Je n'ai pas la fonction de choix "Imprimer le fond" et "Ne peut signer" sur mac, je regarde ca au cabinet demain, voir si il y'a possibilité de faire afficher cette fenêtre sur d'autres pages que la gestion des FSE

**Comment by Refhi** [comment]
#210

**Comment by Refhi** [comment]
Voila !
Du coup : 
- mémorise les paramètres pour "Retirer le fond" et "le patient peut signer"
- imprime direct la FSE avec ctrl+P

=> au final faire une FSE dégradée nécessitera simplement ctrl+P puis alt+V
