### ISSUE TITLE
Enregistrement des options

### ISSUE THREAD

**Issue by DocTigs** [Refhi/Weda-Helper#146]
Bonjour,

Depuis la dernière mise à jour, même en cliquant sur le bouton enregistrer, cela ne sauvegarde pas les modifications réalisées.
J'essaie en particulier d'ouvrir automatiquement l'historique dans une colonne à gauche pour les formulaires (fonctionnalité que je trouve très pratique), mais lorsque je coche la case et que j'enregistre, cela n'est pas suivi d'effet. Et quand je retourne dans les options, elle n'est plus cochée.

**Comment by Refhi** [comment]
Corrigé dans la 2.4 :) (c'est juste l'enregistrement de la fonction pour le formulaire qui était HS, j'ai vu ça hier)
Normalement les autres sont ok ?

**Comment by DocTigs** [comment]
Oui, les autres marchent.
Merci de la réactivité !
