### ISSUE TITLE
Courbes pédiatriques HS si "Activer la navigation entre les valeurs de suivi avec la touche Tab dans les consultations." est décochée

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#149]
problème avec l'option

**Comment by Jitto31** [comment]
![absence courbe](https://github.com/Refhi/Weda-Helper/assets/159796289/74a7a47b-5e24-4627-a44c-9cfca87c7634)
 voila la capture de l'absence des courbe, dans le doute j'ai tenté d'effacer le cache mais pas d'amélioration

**Comment by Refhi** [comment]
Merci
Quelques questions supplémentaires :
- peux-tu faire F12, afficher la console, et chercher la partie où l'on voit "courbesPossiblesFiltered", 'addOvericon' et 'age and gender' stp ?
il faudrait que tu déploie ce qui est noté sous courbesPossiblesFiltered et addovericon, et que tu me copies la capture de la console stp ?
Je veux bien aussi le genre et l'age du patient si c'est pas affiché dans la console

**Comment by Refhi** [comment]
ah, et as-tu changé de style ? (dans https://secure.weda.fr/FolderSetting/MenuSettingForm.aspx dis-moi si de mettre sur "Gris", change quelque chose ?)
est-ce que c'est HS dans plusieurs dossiers pédiatrique ou juste celui-ci ?
merci d'avance pour tes réponses

**Comment by Jitto31** [comment]
j'ai tenté plusieurs style meme gris: pas d'amélioration 
tous les dossier son HS chez moi!
Le bug est aussi sur les autre navigateur
et dans la console j'ai rien de tout ça!! La c'est une fille de 4ans 1/2 mais depuis hier j'ai eu le bug garcon et fille de 15j de vie à 18 ans ! je suis allé voir dans les options si ca c'était pas décoché mais l'option est pas décrochable à priori?? 
Sinon je vais réinstaller l'appli

**Comment by Jitto31** [comment]
ah cest bon j'ai compris!! j'avais décoché "utiliser la touche tab pour la navigation entre les valeurs de suivi"!! ca remarche en le cochant!

**Comment by Refhi** [comment]
Bien vu. Merci pour ton retour, je prépare un correctif pour la 2.5, vu que le problème est contourné en attendant.

**Comment by Refhi** [comment]
Je travaille dessus ici https://github.com/Refhi/Weda-Helper/tree/pediatricBiometry
