### ISSUE TITLE
désactiver "ordonance numérique" si examen radiologique 

### ISSUE THREAD

**Issue by Jitto31** [Refhi/Weda-Helper#150]
décocher "ordonnance numérique " si mot clef "radio" "écho" "IRM" "Scanner" 
si c'est possible??

PS merci pour la pré sélection pour les autre type de demande je n'osai pas le demander vu tout le travail déjà fais^^ vous êtes des génies :-)

**Comment by Abeldvlpr** [comment]
Bonjour !
C’est prévu, je travaille dessus, ça arrive dans la prochaine version à priori

**Comment by Jitto31** [comment]
trop bien tu as pensé à tout ^^
