### ISSUE TITLE
ajout mot-clé type d'ordonnance numérique

### ISSUE THREAD

**Issue by bdoris35** [Refhi/Weda-Helper#151]
Vraiment géniale cette nouvelle fonction ! 
Peut-on rajouter les mots clés semelle / semelles / orthoplastie dans la catégorie pédicure ? 
Encore merci pour le dvpt de ce super outil !

**Comment by Abeldvlpr** [comment]
Bonne idée, je le rajoute dans la prochaine version

**Comment by Refhi** [comment]
J'ai fait un commit, parce que ouvrir une branche juste pour deux mots clés... ^^
