### ISSUE TITLE
petit bug quand activation "Ouvre automatiquement la fenêtre des ordonnances-types lors des prescriptions médicamenteuses"

### ISSUE THREAD

**Issue by bdoris35** [Refhi/Weda-Helper#152]
J'ai activé l'option "Ouvre automatiquement la fenêtre des ordonnances-types lors des prescriptions médicamenteuses" . 
Quand elle est active, qu'on a rajouté un médicament dans l'ordonnance, si on veut rajouter un commentaire en lien avec ce médicament, en cliquant sur la ligne rouge "ajouter un commentaire" sous le nom du médicament, le curseur de saisie de texte reste sur la case de recherche de médicaments. Même si on essaie de cliquer dans la zone de saisie de commentaires, le curseur se remet immédiatement dans la zone de recherche de médicaments. 
J'espère que ma description est claire... 

je rajoute des captures d'écran au cas où

![Capture d'écran 2024-06-29 081644](https://github.com/Refhi/Weda-Helper/assets/174169529/7fbe1ff4-a43c-491e-b155-fbcfef318535)
![Capture d’écran 2024-06-29 081348](https://github.com/Refhi/Weda-Helper/assets/174169529/bd913ae1-1ca5-4511-95b1-95ce437ecf7f)

**Comment by Refhi** [comment]
Oui, très clair, merci pour le ticket, ça vient d'une option de maintient du curseur dans le champ de recherche
je ne crois pas qu'elle soit désactivable
il faut qu'on mette en place une inhibition de ce comportement en cas de détection d'une fenêtre superposée

**Comment by Refhi** [comment]
fix fait :) normalement ok demain matin
