### ISSUE TITLE
La recherche de médicament s'efface

### ISSUE THREAD

**Issue by ced-974** [Refhi/Weda-Helper#154]
Bonjour,

Depuis les 2 dernières MAJ, le nom du médicament entré s'efface et il faut le saisir une deuxième fois.

Cela ne semble arriver qu'une fois après le lancement de Weda, mais comme il faut souvent relancer Chrome / Weda du fait des déconnexions/plantage de page, cela arrive plusieurs fois dans une journée de travail.

Merci,
Cordialement, 
Cédric Le Roux
![Capture d'écran 2024-06-29 115144](https://github.com/Refhi/Weda-Helper/assets/167568069/a843ec54-4135-430e-849d-2d0ea5ad8c3f)
![Capture d'écran 2024-06-29 115213](https://github.com/Refhi/Weda-Helper/assets/167568069/1a61d977-498a-4300-83b1-edd85ca408db)
.

**Comment by Refhi** [comment]
réparé :)
normalement fonctionnel demain, si j'ai bien compris le problème qui se passait chez toi (en gros ton PC est trop rapide ^^)
