### ISSUE TITLE
Raccourcis Control + U

### ISSUE THREAD

**Issue by Philout14** [Refhi/Weda-Helper#156]
Bonjour,
Le raccourcis Control + U pour l'upload du dernier document me pose problème, il remplace le "souligné" dans les cases de texte (oui je l'utilise beaucoup...)
Peut-on le modifier ?

**Comment by Abeldvlpr** [comment]
Bonjour, oui dans les options de l’extension vous avez la possibilité de modifier les raccourcis associés à chaque action. Vous pouvez y accéder en faisant clic droit sur l’extension Weda Helper dans votre navigateur puis « Options »
L’extension est parfois dans une liste auquel vous accédez en cliquant sur un icône en forme de pièce de puzzle

**Comment by Philout14** [comment]
Merci
