### ISSUE TITLE
roadmap 2.4.1 - bugfix

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#157]
- [x] #152
- [x] #153
- [x] #154
- [x] #155
- [x] #149 
- [x] #161

**Comment by Refhi** [comment]
Normalement tout ces bugfix sont anodins, donc je pousse direct

**Comment by Abeldvlpr** [comment]
Ça roule ! Désolé pas d’ordinateur sous la main de tout le week-end, j’ai pas trop pu t’aider..
J’attaque les prochaines features la semaine prochaine

**Comment by Refhi** [comment]
T'inquiète pas 😊
Faut que ça reste un plaisir à faire, pas une contrainte
