### ISSUE TITLE
bug bouton impression manquant dans certificat si affichage historique activé 

### ISSUE THREAD

**Issue by bdoris35** [Refhi/Weda-Helper#161]
lorsque l'option "Ouvrir automatiquement l'historique dans les pages sélectionnées ci-dessous et l'afficher dans une colonne à gauche." est activée pour les **certificats**, la colonne d'icones permettant notamment d'imprimer n'apparait plus,
et derrière la zone de gauche (qui affiche l'historique) on devine la phrase de texte "un médecin ne doit jamais donner un certificat sans avoir vu et examiné la personne dont il s'agit ..." (on arrive à la lire juste avant que l'historique s'affiche!) qui est normalement placée sous la zone de texte des certificats quand l'option d'historique n'est pas activée 

![Capture d'écran 2024-06-30 183911](https://github.com/Refhi/Weda-Helper/assets/174169529/321e8757-bb14-4583-adcc-16e33ef7c55a)

**Comment by Refhi** [comment]
merci pour le bug report, je venais d'ouvrir un ticket 4 minutes avant toi ^^
#160

**Comment by bdoris35** [comment]
oui j'ai vu ça juste après avoir posté mon ticket !

**Comment by Refhi** [comment]
Ce sera fix demain matin normalement :)
