### ISSUE TITLE
Perte curseur lors prescription d'une demande avec l'historique affiché

### ISSUE THREAD

**Issue by tpuszkarek** [Refhi/Weda-Helper#168]
Bonjour,
Merci de tout votre travail !
Ce n'est qu'un détail mais, depuis avec la dernière version de Weda Helper, je perds la possibilité de rédiger une "demande" si l'historique est affiché à gauche.
Cela fonctionne parfaitement si je désactive l'affichage de l'historique dans les options.
Merci encore !

**Comment by Refhi** [comment]
Bonjour,
Merci pour les encouragements

Peux-tu nous joindre dès captures d'écran stp ?
Ainsi que si possible le log dans la console (F12 ou ctrl+shift+c Puis console ) stp ?

Je regarde tout à l'heure

**Comment by tpuszkarek** [comment]
Voilà !
Même en cliquant dans la zone de texte, impossible de saisir quoi que ce soit.
![weda1](https://github.com/Refhi/Weda-Helper/assets/158053494/a10de94c-d142-478c-8929-b569f3f557a1)
![weda2](https://github.com/Refhi/Weda-Helper/assets/158053494/bf46a3eb-ca1f-41f6-ad12-f359210d16fc)

**Comment by DrFloW71** [comment]
Idem chez moi sur les courriers et demandes.  
![Bug](https://github.com/Refhi/Weda-Helper/assets/157386513/44837f0e-11d1-40c0-93f7-30e6a8963c57)

**Comment by bdoris35** [comment]
en pratique on ne peut surtout plus cliquer nulle part sur une large partie de la page web dans les certificat et demandes et courriers lorsque l'affichage de l'historique est activé
je mets en copie d'écran la zone qui n'est plus '"cliquable" 
évidemment on ne peut pas imprimer non plus puisqu'on ne peut pas cliquer !

![copie erreur](https://github.com/Refhi/Weda-Helper/assets/174169529/51aa130c-2ac4-4324-9d00-5015d140f612)

**Comment by Refhi** [comment]
On corrige ça ce soir :-/
En attendant vaut mieux désactiver l'historique à gauche sur ces pages...

**Comment by DrFloW71** [comment]
Yes en désactivant ça refonctionne bien.

**Comment by Refhi** [comment]
réparé dans la 2.4.2, qui devrait arriver chez vous au plus tard demain matin
merci pour votre patience !
