### ISSUE TITLE
Améliorer detection de fichier dans messagerie securisé

### ISSUE THREAD

**Issue by Jitto31** [Refhi/Weda-Helper#171]
Bonjour
de mon coté l'option " Décocher automatiquement le message et le fichier IHE_XDM.zip lors de l'importation d'un message depuis la messagerie sécurisée" décoche tous les fichiers!

par exemple pour ce message:
Le fichier IHE_XDM.zip est décoché: TOP
Le fichier LIFEN est décoché (tant mieux mais il me semble pas que c'était le but?? mais si il reste décoché ca m'arrange^^))
Par contre le courrier qui m'intéresse le "compte rendu" est aussi décoché: est ce normal? 

 Je ne sais pas si les diffèrent type de fichier son facile à cibler d'où peut être le fait qu'ils se décochent tous?

![2024-07-02 11_54_11-Echanges](https://github.com/Refhi/Weda-Helper/assets/159796289/87f85242-c0f3-4fab-a4b2-5325a6c6408e)
![2024-07-02 11_53_59-Echanges](https://github.com/Refhi/Weda-Helper/assets/159796289/eb5061b1-6d25-476b-a394-34cd364c712e)
![2024-07-02 11_54_27-Echanges](https://github.com/Refhi/Weda-Helper/assets/159796289/93ca1231-fe25-4086-bfa9-794d404f458e)

**Comment by Jitto31** [comment]
sur mon exemple en gros il faudrait qu'il garde coché que le fichier PDF et décoche le reste (ZIP et message sans PDF) mais je ne sait pas si c'est valable pour tout le monde tout le temps??

**Comment by Abeldvlpr** [comment]
En effet ce n’est pas le comportement normal. Est ce que vous avez ce bug sur tous les courriers que vous importez ou seulement sur certains ?

**Comment by Abeldvlpr** [comment]
J’aurai besoin de savoir quelle type de messagerie vous utilisez et si vous devez vous y connecter avec la CPS à chaque fois ou non ?
Tout fonctionne correctement de mon côté mais j’ai une installation des échanges sécurisés un peu particulière

**Comment by Jitto31** [comment]
c'est le cas pour tout les courrier, j'utilise MEDIMAIL, pas besoin de lire la CPS à chaque fois!

**Comment by Abeldvlpr** [comment]
Ok ! Est ce que tu serai disponible demain dans la matinée ou dans l’après midi pour faire un TeamViewer ou Anydesk que je regarde le problème directement sur ton installation Weda ?

**Comment by Jitto31** [comment]
Oui bien sûr, je serai au cabinet me matin donc je pourrais laisser l'accès en anydesk, je met mon numéro d'accès demain matin ici si tu veux ?

**Comment by Jitto31** [comment]
mon poste anydesk: Bonjour,

Je vous invite à rejoindre ma session AnyDesk. Mon ID est 490 763 850.

**Comment by Abeldvlpr** [comment]
Est ce que tu es disponible vers 10h15 ?

**Comment by Jitto31** [comment]
oui tres bien!

**Comment by Jitto31** [comment]
docImportAttach ng-star-inserted

**Comment by Jitto31** [comment]
"J'ai trouvé d'où cela vient, je corrige ca dans la prochaine version, merci à vous _"

Super merci à toi! bonne journée

**Comment by Abeldvlpr** [comment]
Fix dans 71f27e9
