### ISSUE TITLE
Tabulation entre les zones de texte d'une consultation ?

### ISSUE THREAD

**Issue by tpuszkarek** [Refhi/Weda-Helper#174]
Bonjour,
Juste une idée : que penseriez-vous de permettre qu'appuyer sur la touche "tabulation" permette de basculer entre les différentes zones de texte d'une consultation ?
A nouveau, mille merci pour tout ce que vous faites !

**Comment by Abeldvlpr** [comment]
Bonjour !
Très bonne idée. Nous l’avons déjà envisagée (voir #131 ) et c’est en cours.
Je me permets de fermer ce commentaire pour ne pas faire doublon et que ce soit plus simple à gérer pour nous.
