### ISSUE TITLE
Ajout d'une option pour décocher automatiquement la case Ordonnance Numérique lorsque la demande est une demande d'imagerie

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#179]
Fait pour prendre la suite de la cloture de #95

**Comment by Refhi** [comment]
@Abeldvlpr je suis partit sur détecter si "Imagerie" est en rouge, avec l'avantage de la simplicité.
Si tu souhaitais repartir sur le système de détection de mots-clés n'hésite pas :)

**Comment by Abeldvlpr** [comment]
Je viens de tester ca me semble être la meilleur solution et ca fonctionne très bien !
