### ISSUE TITLE
Ajouter un message d'alerte en cas de contre-indication médicamenteuse absolue

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#182]
Les interactions médicamenteuses étant très mal affichées par Weda, il pourrait être pratique d'afficher un message d'alerte plus important lorsqu'une prescription médicamenteuse présente une contre-indication absolue (correspond à un icone de classe `imgInter4`)

**Comment by Abeldvlpr** [comment]
<img width="1552" alt="Capture d’écran 2024-07-08 à 00 49 08" src="https://github.com/Refhi/Weda-Helper/assets/300872/d638505b-e93c-4049-a72b-05cf8292c037">

Un exemple de ce à quoi cela peut ressembler

**Comment by Abeldvlpr** [comment]
@Refhi qu'est-ce que tu en penses ? Je pensais le mettre en option et le limiter au niveau 4 (= CI absolue) et éventuellement laisser l'option à chacun de choisir pour quel niveau il veut une alerte

**Comment by Abeldvlpr** [comment]
https://github.com/Refhi/Weda-Helper/tree/interactions

**Comment by Refhi** [comment]
J'aime bien l'idée !

**Comment by Abeldvlpr** [comment]
Je te laisse regarder si l'implémentation te va et voir si on l'intègre dans la 2.5 ?

**Comment by Refhi** [comment]
n'hésite pas à faire une PR à partir de la branche, c'est plus facile pour faire la revue du code si tu veux bien :)

**Comment by Abeldvlpr** [comment]
Oui c'est plus propre et plus pratique, je le ferai pour les prochains ajout de feature !

**Comment by Refhi** [comment]
intégré à la 2.5
je propose de figer les choses à travailler sur la 2.5 afin de se concentrer sur les bugfix

**Comment by Abeldvlpr** [comment]
Ok pour moi !
