### ISSUE TITLE
Z score IMC ? 

### ISSUE THREAD

**Issue by NPilgrimm** [Refhi/Weda-Helper#184]
Bonjour, au sein de notre MSP, nous avons besoin de calculer le Z score IMC, qui permet de déterminer si un enfant est en surpoids, et s'il s'améliore au fil des mois. C'est très important, car les seuils d'IMC définissant le surpoids ou l'obésité changent continuellement avec l'âge, et donc le seul critère de suivi IMC ne permet pas d'identifier automatiquement ces patients en surpoids ou obèses, ni de suivre leur évolution de manière fiable. 
Ci-joint un fichier excel qui permet de faire ce calcul.  Pensez-vous qu'il soit possible d'intégrer cette mesure dans les tableaux de suivi des patients ? 

[Calculs IMC Zscore et Corpulence pour cohorte_module APOP_2023.xlsx](https://github.com/user-attachments/files/16125231/Calculs.IMC.Zscore.et.Corpulence.pour.cohorte_module.APOP_2023.xlsx)

Merci d'avance pour votre éclairage ! 

Dr Nicolas Pellegrin

**Comment by Refhi** [comment]
Ok, j'ai commencé à regarder l’algorithme présent dans le fichier excel, et ça va demander pas mal de rétro-ingénierie, mais c'est probablement faisable.
A-t-on une biblio pour attester de la fiabilité de ce score ?
Encore mieux, aurais-tu directement la formule de calcul ?

@Abeldvlpr au passage aurais-tu une idée pour récupérer directement le Z score depuis les courbes pédiatriques officielles ?

**Comment by Refhi** [comment]
[calcule.pdf](https://github.com/user-attachments/files/16313492/calcule.pdf)

=> à évaluer

**Comment by Abeldvlpr** [comment]
Ça a l’air fun 😂

**Comment by Jitto31** [comment]
j'ai rien compris 😅ca recalcul un IMC plus fiable?? C'est des nouvelles courbes d'IMC plus fiable??

**Comment by Refhi** [comment]
@Jitto31 ce que j'en comprend c'est que ça permet de plus facilement interpréter l'IMC chez les enfants d'un coup d'oeil sans forcément ouvrir la courbe pédiatrique qui te permet de localiser l'IMC par rapport à la norme.

**Comment by NPilgrimm** [comment]
Oui ça permet de déterminer automatiquement le surpoids et l'obésité chez les enfants (car le seuil de définition dépendant de l'âge, sans ce score on est obligé de se reporter à la courbe, puis coder un antécédent cim-10 pour que le logiciel comptabilise le patient comme en surpoids ou obèse et permette des statistiques sur la patientèle) . De plus, pour un enfant obèse, ça permet de donner un indicateur de suivi qui détermine si l'écart avec la courbe d'IMC normal s'aggrave ou s'améliore d'une consultation à l'autre


Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Refhi** [comment]
J'ai *un peu* galéré pour comprendre l'algorithme et la table de référence, mais c'est fait !

Vous pouvez tester avec https://github.com/Refhi/Weda-Helper/archive/ee06e698dd02422fe80475d3f5fa8f10fe40d9ca.zip si vous voulez (mode dev dans chrome) cf. https://github.com/Refhi/Weda-Helper/issues/194#issuecomment-2248495000 pour la procédure pour tester avant la publication de la 2.6).

Le seul soucis, c'est le même que pour les courbes pédiatriques : il faut enregistrer (ou faire ctrl+S) pour que les valeurs du jour soient prises en compte.
