### ISSUE TITLE
Améliorer REGEX pour type d'ordonnance numérique

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#187]
Le regex actuel détecte "acide urique" comme infirmier en raison de la présence d'IDE.
Il faut adapter le Regex pour qu'il ne reconnaisse IDE que comme un mot seul

**Comment by Refhi** [comment]
On a aussi la problématique de :
"faire pratiquer par IDE à domicile :
NFS etc."
=> c'est labo ou IDE ?
Je pense qu'il faut déclencher le regex que quand on est dans "paramédical" du coup ?

**Comment by Refhi** [comment]
est-ce qu'on rajoute aussi la détection des mots clé "domicile" pour cocher la case  "soin à réaliser à domicile" dans les ordos numériques ?

**Comment by Abeldvlpr** [comment]
Excellente idée pour les deux !

**Comment by Refhi** [comment]
> Excellente idée pour les deux !

enfin sauf que pour détecter "domicile" il faudra quand même un minimum de regex, même pour "Laboratoire" ^^

**Comment by Abeldvlpr** [comment]
C'est implémenté dans c3d286b
Je te laisse tester. Je pense avoir compris pourquoi cela ne fonctionnait pas chez toi. Au moment de l'impression, l'iframe du contenu de la prescription est rechargé et mon bout de code récupère un contenu de prescription vide et donc aucun Regex ne fonctionnait.
J'ai ajouté un délai de 200ms, je te laisse tester et me dire si ca fonctionne bien pour toi.

Ces iframe vont vraiment nous casser les pieds jusqu'au bout !!

**Comment by Refhi** [comment]
en effet
je suis en train de faire un gros refactory de cette partie avec une amélioration de lightObserver (en reprenant le code que tu as fait)
j'ouvre une branche et un pr dès que c'est plus propre

**Comment by Refhi** [comment]
#191 j'ai fait ça, je te laisse vérifier ce que ça donne, mais a priori ça fonctionne plutôt bien
je le merge, mais on peut facilement unmerge si ça coince
je laisse le ticket ouvert en attendant
et effectivement fichues iframes... vivement que tout passe en Angular...

**Comment by Refhi** [comment]
ça coince pour les ordo bizones, faudrait qu'on rajoute l'analyse des deux champs de texte

**Comment by Abeldvlpr** [comment]
C'est tout bon de mon côté !
