### ISSUE TITLE
Cocher Gestion unique ne fonctionne pas bien

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#188]
Coche également Domicile mais que certaines fois

**Comment by Abeldvlpr** [comment]
Ajouter un check que le texte associé à la checkbox contient bien "Réaliser une FSE en gestion unique"

**Comment by Abeldvlpr** [comment]
Fixé de manière un peu sale dans 8b4686e

**Comment by Refhi** [comment]
ouch en effet c'est sale, mais j'approuve ^
