### ISSUE TITLE
impossible de décocher "ordonnance numérique" manuellement

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#189]
si l'option " Décoche automatiquement l'ordonnance numérique si "Imagerie" est sélectionné dans une Demande." est activée

**Comment by Abeldvlpr** [comment]
Oui c’est le problème qu’on avait eu avec la première implémentation.. la solution c’est de changer la catégorie d’ordonnance pour pouvoir le cocher.
Ce qu’on peut essayer d’implémenter c’est un Check qui détecte si la case a été cochée par l’utilisateur et de mettre un flag pour pas la re décocher derrière.
Faut voir au niveau des évent JS si on peut voir la trace qui a déclenché l’event

**Comment by Abeldvlpr** [comment]
J'ai regardé, tout le DOM est rechargée au moment où l'on recoche la case ordonnance numérique... Je ne vois pas de solution évidente.
Après c'est le comportement attendu et il n'y a pas de situation où l'on voudra faire une ordonnance numérique d'imagerie, la solution reste de choisir un autre type de demande dans le panneau latéral.
Qu'est-ce que tu en penses ?

**Comment by Refhi** [comment]
fix fait dans https://github.com/Refhi/Weda-Helper/commit/0908bd10ee3064c4e807503dd9c1909d6617f36c :)
J'ai contourné le problème en modifiant l'écoute de la case à cocher
