### ISSUE TITLE
Volet atcd dans les imports

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#194]
ça avait été demandé à un moment, mais rejeté.

Mais maintenant qu'on est plus à l'aise avec les iframes, ça pourrait peut-être être possible ?

**Comment by Abeldvlpr** [comment]
Ah oui excellente idée ça ! Faut voir à quel point on peut faire rentrer toute la page antécédents dans une iframe

**Comment by Refhi** [comment]
ah oui c'est vrai que c'est un gros morceau...
on pourrais envisager une iframe déclenchée via un clic sur un bouton associé au patient ?

**Comment by DrFloW71** [comment]
Salut effectivement c'est moi qui avait proposé ça. C'est tellement chiant de lire un nouvel antécédent sur un courrier et d'être obligé d'ouvrir le dossier, aller dans les antécédents et le rentrer à ce moment-là. Si tout pouvait se faire depuis la page d'import ça serait quand même beaucoup plus pratique! Je ne peux hélas pas faire grand-chose à part vous encourager 😂

**Comment by Refhi** [comment]
J'aurais besoin d'un peu d'aide pour mieux conceptualiser cette fonction :
- dans quelles pages en aurions-nous besoin ? Seulement https://secure.weda.fr/FolderMedical/UpLoaderForm.aspx ou d'autres également ? Si également dans les échanges sécurisés ou autre, j'aurais besoin des URL, et de quelques screenshot si possible
- ferions-nous simplement un raccourcis vers la page des antécédents ou une iframe qui se déploierais depuis un survol du nom du patient ? Autre ?

J'attends vos remarques avant d'avancer sur la thématique :)

**Comment by Jitto31** [comment]
moi je dirais sur cette page aussi https://secure.weda.fr/FolderMedical/WedaEchanges/
c'est par la que j'intègres les courrier personnellement et beaucoup le font j'imagine, 

une iframe serait le top si ca se permet de modifier les antécédents sans changer de page!

**Comment by Jitto31** [comment]
j'ai fais 3 capture d'écran: 
1- quand on ouvre le courrier
2-quand on cherche le patient: une page s'ouvre par dessus le courrier (on le voit en arrière plan le courrier) pour chercher le patient 
3-Une fois le patient sélectionner (on ne voit pas le patient en évidence) on a juste la possibilité de cliquer sur le fichier qu'on veut envoyer chez le patient.> Cest à ce moment qu'un bouton qui ouvrirait une fenêtre par dessus directement dans le volet antécédant du patient qui serait intéressant pour le mettre à jour
+/- un autre bouton pour créer directement une alerte dans le dossier patient?? (l'horloge sur la fiche patient?)

En tout cas ca serait top!
![alerte](https://github.com/user-attachments/assets/da2d7057-e61e-4915-b8d4-3f1ececd57e1)
![2024-07-22 17_45_59-](https://github.com/user-attachments/assets/c08320f0-5fcd-4615-b5e6-794eefdc1e5b)
![2024-07-22 17_45_22-](https://github.com/user-attachments/assets/2ec8cad8-1fbe-45fb-8ce6-6565252595eb)
![2024-07-22 17_44_51-Paramètres](https://github.com/user-attachments/assets/680efd30-86fa-4b6d-ab65-5b7f1cc276f4)

**Comment by DrFloW71** [comment]
La proposition de @Jitto31 pour la page https://secure.weda.fr/FolderMedical/WedaEchanges/ me semble parfaite!

**Comment by Refhi** [comment]
La solution la plus simple que je verrais, c'est qu'une action donnée (clic du milieu de la souris ?) sur le nom d'un patient (dans la liste de recherche des patients) ouvrirais directement sa page atcd dans un nouvel onglet, et qu'un clic droit ouvre la fenêtre de rappel.
Je vais voir si c'est techniquement accessible.

**Comment by Refhi** [comment]
Hey !

Je pense que ça pourrais vous plaire :
https://github.com/Refhi/Weda-Helper/archive/refs/tags/v2.6-alpha-atcdnotes.zip

J'ai testé sur la page de recherche et la page d'import, mais pas pu tester dans wedaConnect, je peux vous laisser faire ?
=> un simple clic du milieu ou clic droit permet d'accéder aux pages pertinentes :)

=> je vous invite à tester :
Pour l'essayer :
- aller dans chrome://extensions/
- désactiver Weda Helper - ID : dbdodecalholckdneehnejnipbgalami
- activer le mode développeur
- cliquer sur "Charger l'extension non empaquetée" et sélectionne le zip précédemment téléchargé

=> quand le test est fini, je vous invite à la supprimer puis à réactiver Weda Helper  - ID : dbdodecalholckdneehnejnipbgalami

Tenez-moi au courant ^^

**Comment by DrFloW71** [comment]
Salut, testé sur cette page: https://secure.weda.fr/FolderMedical/WedaEchanges/

Le clic droit et clic molette ne font rien. Il y a une subtilité pour la zone ou cliquer?

**Comment by Jitto31** [comment]
top!
testé a l'instant ca marche super bien!
Merci :-)

**Comment by DrFloW71** [comment]
> top! testé a l'instant ca marche super bien! Merci :-)

Tu fais comment?

**Comment by Jitto31** [comment]
> > top! testé a l'instant ca marche super bien! Merci :-)
> 
> Tu fais comment?

>tu as réussi à installer la version béta?  > il faut bien suivre la démarche de Refhi:

1/Télécharger:
"https://github.com/Refhi/Weda-Helper/archive/refs/tags/v2.6-alpha-atcdnotes.zip
2/>extraire le fichier

3/aller dans chrome://extensions/
4/désactiver Weda Helper - ID : dbdodecalholckdneehnejnipbgalami
5/activer le mode développeur
6/cliquer sur "Charger l'extension non empaquetée" et sélectionne le zip précédemment téléchargé


=> quand le test est fini, je vous invite à la supprimer puis à réactiver Weda Helper - ID : dbdodecalholckdneehnejnipbgalami"

**Comment by DrFloW71** [comment]
> > > top! testé a l'instant ca marche super bien! Merci :-)
> > 
> > 
> > Tu fais comment?
> 
> > tu as réussi à installer la version béta?  > il faut bien suivre la démarche de Refhi:
> 
> 1/Télécharger: "https://github.com/Refhi/Weda-Helper/archive/refs/tags/v2.6-alpha-atcdnotes.zip 2/>extraire le fichier
> 
> 3/aller dans chrome://extensions/ 4/désactiver Weda Helper - ID : dbdodecalholckdneehnejnipbgalami 5/activer le mode développeur 6/cliquer sur "Charger l'extension non empaquetée" et sélectionne le zip précédemment téléchargé
> 
> => quand le test est fini, je vous invite à la supprimer puis à réactiver Weda Helper - ID : dbdodecalholckdneehnejnipbgalami"

Oui pas de souci pour installer la bêta mais quand je suis sur la page d'import des courriers le clic droit n'ouvre pas les ATCD.

**Comment by Jitto31** [comment]
> > > > top! testé a l'instant ca marche super bien! Merci :-)
> > > 
> > > 
> > > Tu fais comment?
> > 
> > 
> > > tu as réussi à installer la version béta?  > il faut bien suivre la démarche de Refhi:
> > 
> > 
> > 1/Télécharger: "https://github.com/Refhi/Weda-Helper/archive/refs/tags/v2.6-alpha-atcdnotes.zip 2/>extraire le fichier
> > 3/aller dans chrome://extensions/ 4/désactiver Weda Helper - ID : dbdodecalholckdneehnejnipbgalami 5/activer le mode développeur 6/cliquer sur "Charger l'extension non empaquetée" et sélectionne le zip précédemment téléchargé
> > => quand le test est fini, je vous invite à la supprimer puis à réactiver Weda Helper - ID : dbdodecalholckdneehnejnipbgalami"
> 
> Oui pas de souci pour installer la bêta mais quand je suis sur la page d'import des courriers le clic droit n'ouvre pas les ATCD.

Ah oui j'avais pas compris ce qui marchait pas!

C'est quand on lance la recherche patient, sur le nom du patient dans la liste qu'il faut faire clic droit et clic milieux :-)

**Comment by Refhi** [comment]
@DrFloW71 Tu peux m'envoyer une capture d'écran avec la console stp ?

**Comment by DrFloW71** [comment]
Ah OK je n'utilisais pas correctement. @Refhi et @Abeldvlpr serait il possible d'avoir la même chose directement sur la page d'import https://secure.weda.fr/FolderMedical/WedaEchanges/ une fois la patient choisi? Car la plupart du temps le prématching (qq propositions de patients) est automatique par Weda et pas besoin de faire une recherche.

![image](https://github.com/user-attachments/assets/cf9519d2-49cc-4961-ab3c-1e10b938d273)

**Comment by Jitto31** [comment]
"? Car la plupart du temps le prématching (qq propositions de patients) est automatique par Weda et pas besoin de faire une recherche"
>> Comment?? Weda me propose rien moi je suis toujours obligé de le chercher manuellement ^^ Il s'affiche ou le pré matching?

**Comment by DrFloW71** [comment]
> @DrFloW71 Tu peux m'envoyer une capture d'écran avec la console stp ?

Voici:

![image](https://github.com/user-attachments/assets/4c6dfeba-9260-4448-956c-d9a022ef46ca)

Logs:
024-07-25 14:23:24 OPTIONS / 200 OK
2024-07-25 14:23:24 homepage requested
2024-07-25 14:23:24 GET / 200 OK
2024-07-25 14:28:11 GET /log 200 OK
2024-07-25 14:28:11 Clé API non fournie
2024-07-25 14:28:11 GET /favicon.ico 200 OK

**Comment by Refhi** [comment]
merci, je vois le problème.

Mon soucis c'est que je n'ai pas weda-exchange, du coup c'est difficile à coder... @Abeldvlpr  est-ce que tu pourrais éventuellement t'en charger ?

**Comment by Jitto31** [comment]
Bonjour, en classant les bio, j eme suis dis que le meme principe clic droit et milieu pour aller dans les antécédant et le salertes seraient pas mal! au niveau de "onglet "nom du patient" clic droit rappel dans l'onglet, clic milieu antecedant et clic gauche ca ouvre comme d'habitude l'onglet patient

je ne sais pas si c'est galere de transposer la fonction sur cette page aussi ^^

merci!!

**Comment by Refhi** [comment]
> Bonjour, en classant les bio, j eme suis dis que le meme principe clic droit et milieu pour aller dans les antécédant et le salertes seraient pas mal! au niveau de "onglet "nom du patient" clic droit rappel dans l'onglet, clic milieu antecedant et clic gauche ca ouvre comme d'habitude l'onglet patient
> 
> je ne sais pas si c'est galere de transposer la fonction sur cette page aussi ^^
> 
> merci!!

Oui, ça c'est simple à ajouter, je m'en occupe

**Comment by Refhi** [comment]
à tester mais ça à l'air pas mal :
https://github.com/Refhi/Weda-Helper/releases/tag/v2.6-alpha-atcdnotes2
n'hésitez pas à me dire si ça correspond bien à ce que vous attendiez, ou si il faut affiner la présentation

**Comment by Jitto31** [comment]
j'ai testé sur un patient mais ca na pas fonctionné, sauf que j'ai plus de résultats^^je retesterai plus tard!

**Comment by Refhi** [comment]
n'hésite pas à me dire
J'ai mis le clic droit/milieu sur l'endroit où ça déclenche normalement l'ouverture de l'onglet ou du dossier patient, n'hésite pas à essayer
Je verrais peut-être pour étendre la zone cliquable pour plus de facilité

**Comment by Jitto31** [comment]
ca ne marche pas donc 2 possibilité:
->je ne charge pas le bon package , je suis pas sure d'avoir les bon fichier car même dans les medimail ca ne marche pas alors que ca fonctionnait bien avec l'autre beta?? et en plus ca s'appelle version 2.5 au lieu de 2.6 comme sur le nom du lien?? 

->je clic pas au bon endroit mais j'ai cliqué à tout les endroit imaginable^^

**Comment by Refhi** [comment]
normalement c'est marqué 2.5.9....

**Comment by Jitto31** [comment]
non la c'est 2.5; mais il n'y a pas de problème ^^ je ferai les test plus tard pour confirmer le bon fonctionnement!  
![2024-07-26 17_32_48-Extensions](https://github.com/user-attachments/assets/272d23a6-42ba-41a7-a732-5ffaba960753)

**Comment by Refhi** [comment]
=> voilà https://github.com/Refhi/Weda-Helper/archive/refs/tags/v2.6-alpha2.zip
c'était pas la bonne...

**Comment by Refhi** [comment]
pour l'instant je ferme le ticket, étant probablement correctement résolu.

Je vais bientôt mettre la 2.6 en phase de test, que je devrait publier d'ici 1-2 semaine si tout va bien. N'hésitez pas à me dire si vous voyez des bugs en attendant.

**Comment by DrFloW71** [comment]
> "? Car la plupart du temps le prématching (qq propositions de patients) est automatique par Weda et pas besoin de faire une recherche"
> 
> > > Comment?? Weda me propose rien moi je suis toujours obligé de le chercher manuellement ^^ Il s'affiche ou le pré matching?

Ca resemble à ça avec les noms qui ressemblent à ce que Weda détecte dans le courrier. Il y a une petite liste et tu choisis le bon. Ca évite de faire une recherche:

![image](https://github.com/user-attachments/assets/d5968707-7c12-47f8-b3f1-54dae5a52c26)

**Comment by DrFloW71** [comment]
> pour l'instant je ferme le ticket, étant probablement correctement résolu.
> 
> Je vais bientôt mettre la 2.6 en phase de test, que je devrait publier d'ici 1-2 semaine si tout va bien. N'hésitez pas à me dire si vous voyez des bugs en attendant.

Testé à l'instant et ça marche super bien! Trop pratique!!! Le seul souci c'est moi qui suis un peu dyspraxique pour cliquer sur la molette ^^

**Comment by Refhi** [comment]
Je ré-ouvre car je vois quand même quelques pistes d'amélioration : @DrFloW71 
- est-ce que remplacer, ou permettre en +, un ctrl+clic à la place du bouton du milieu te paraitrait intéressant ? (c'est vrai que le bouton molette est pas toujours évident)
- est-ce que je tente une harmonisation des différents points d'implémentation pour qu'à chaque fois on puisse faire les 3 actions (ouverture dossier/atcd/note) au niveau du nom/prénom plutôt que parfois dessus et parfois sur "ouvrir" comme dans HPRIM ?

**Comment by DrFloW71** [comment]
Effectivement CTRL + clic G ou D me semble plus simple et une harmonisation est une excellent idée!!!

**Comment by Jitto31** [comment]
> > "? Car la plupart du temps le prématching (qq propositions de patients) est automatique par Weda et pas besoin de faire une recherche"
> > > > Comment?? Weda me propose rien moi je suis toujours obligé de le chercher manuellement ^^ Il s'affiche ou le pré matching?
> 
> Ca resemble à ça avec les noms qui ressemblent à ce que Weda détecte dans le courrier. Il y a une petite liste et tu choisis le bon. Ca évite de faire une recherche:
> 
> ![image](https://private-user-images.githubusercontent.com/157386513/352960421-d5968707-7c12-47f8-b3f1-54dae5a52c26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTI4NTMsIm5iZiI6MTcyMjI1MjU1MywicGF0aCI6Ii8xNTczODY1MTMvMzUyOTYwNDIxLWQ1OTY4NzA3LTdjMTItNDdmOC1iM2YxLTU0ZGFlNWE1MmMyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxMTI5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDUxNzY1NGI3MjIwOWYwNTk0ZDE1NTg4MDkyYmQ5MDJlZTAzNWE1MjkwY2RjZDE2ZGE0NjMwODFiYzI0MGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gC6ythpwQIENH_fgvrGQ4DrCw_ijG_9f1d26yTbnJas)



Trop bizarre ça marche avec aucun courriel moi! Même pour les message lifen ca ne marche pas! Tu as quel prestataire? MAILIZ? Je suis sur MEDIMAIL moi peut etre medimail qui n'est pas au norme?

**Comment by DrFloW71** [comment]
Je suis uniquement sur MSsanté (Mailiz à priori).

**Comment by Refhi** [comment]
voilà, si tu veux essayer, j'ai ajouté le ctrl+clic, ainsi que l'extension de la zone avec ce raccourcis au nom dans hprim

https://github.com/Refhi/Weda-Helper/archive/e121280418d7c6743b8146acbc79766629c57e8d.zip

**Comment by Refhi** [comment]
Du coup je cloture, mais n'hésitez pas à me dire si vous constatez des bugs

**Comment by DrFloW71** [comment]
Salut! Alors ça marche super dans l'import de courriers. Je trouve le CTRL + clic bien plus pratique. par contre ne fonctionne pas sur la page import de bio HPRIM:
![image](https://github.com/user-attachments/assets/258c2628-68a3-44fb-b49c-4b462f604ae9)

**Comment by Refhi** [comment]
ah, oui, c'est normal, pour HPRIM c'est à droite après avoir cliqué sur le patient :
![image](https://github.com/user-attachments/assets/65e93d79-5249-4a11-ae7b-991829ffbf84)

**Comment by DrFloW71** [comment]
> ah, oui, c'est normal, pour HPRIM c'est à droite après avoir cliqué sur le patient : ![image](https://private-user-images.githubusercontent.com/2778215/353554057-65e93d79-5249-4a11-ae7b-991829ffbf84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDkyNDMsIm5iZiI6MTcyMjQwODk0MywicGF0aCI6Ii8yNzc4MjE1LzM1MzU1NDA1Ny02NWU5M2Q3OS01MjQ5LTRhMTEtYWU3Yi05OTE4MjlmZmJmODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMDY1NTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDMyMDExOTUyYTM3ZWI2OWFmZGUzNDA0NWI0ZTA4MTYwMmNhZThmMGYwN2NiMTU0NTI1MTI0ZjMxZjkwZjA2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fdgk7i2pxfgb02YJjWVhY8P9cY4Mup0sWoCj2X5-R1w)

Parfait, fonctionne au top, après avoir importé pas mal de choses ce matin tant bio que courriers, je vous confirme que cette nouvelle fonctionnalité est très pratique!
