### ISSUE TITLE
Cocher par défaut "vertical" et "afficher la zone commentaire"

### ISSUE THREAD

**Issue by Adrien-Pey** [Refhi/Weda-Helper#195]
Bonjour,
Dans la section "télécharger des documents" serait-il possible de cocher par défaut les options "vertical" et "afficher la zone commentaire" ?
Merci

**Comment by Refhi** [comment]
Grâce à toi je viens de découvrir ces possibilités !
Oui c'est largement faisable, on voit ça pour la 2.6

**Comment by Abeldvlpr** [comment]
Bonjour ! De mon côté, ces cases restent déjà cochées automatiquement une fois que je les ai cochés. Observez-vous le même comportement ?

**Comment by Adrien-Pey** [comment]
De mon côté, quand je coche les cases, elles restent cochées tant que mon navigateur internet (chromium) n'est pas fermé. Donc je recoche les cases tous les jours.

**Comment by Jitto31** [comment]
en effet moi aussi elle reste cochée!
Ce n'est pas un soucis de permission sur les cookies (cookies supprimés??)

**Comment by Adrien-Pey** [comment]
Exact c'est résolu. C'était une histoire d'autoriser les cookies pour "secure.weda.fr". Merci
