### ISSUE TITLE
Accés direct au dossier patient depuis l'agenda

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#196]
Ouvrir le dossier patient en faisant un clic droit sur le RDV dans l'agenda.

Idée proposée ici: https://communaute.weda.fr/t5/Entraide-Logiciel-Weda/Weda-Helper-et-Weda-Helper-Companion/m-p/5246/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufExZSVlXUkdBUTVHWkRMfDUyNDZ8U1VCU0NSSVBUSU9OU3xoSw#M1217

**Comment by Refhi** [comment]
N'utilisant pas le planning intégré, je te laisse celui-là :)
