### ISSUE TITLE
Permettre à la facturation par défaut de fonctionner après un clic sur les questions Oui/non + clarifier raccourcis

### ISSUE THREAD

**Issue by ErreipZeyob** [Refhi/Weda-Helper#198]
j'ai bien suivi les instruction en créant un favori "Défaut" et relancé Weda Compagnon et Weda Helper mais ne fonctionne pas

**Comment by Abeldvlpr** [comment]
Bonjour, pour déclencher la cotation par défaut il faut utiliser les raccourcis claviers Non (lettre n) ou Oui (lettre o) pour répondre aux questions « Accident de droit commun » et « Soins dans le cadre de l’ALD »
Une fois ces questions répondus en utilisant les lettres o ou n, la cotation par défaut sera automatiquement selectionée

**Comment by Refhi** [comment]
est-ce qu'on voit pour le déclencher un peu plus facilement dès que la case est cochée plutôt qu'avec l'écoute des raccourcis claviers, ou est-ce qu'on laisse comme ça pour inciter à l'usage des raccourcis ?

**Comment by Abeldvlpr** [comment]
Personnellement je serai pour le passer en automatique sans passer par les raccourcis, faut voir si ça fait pas buguer l’interface de calcul du tarif si on met la cotation avant d’avoir coché non..

Mais c’est vrai que c’est pas le premier retour que l’on a sur cette fonctionnalité et ça met parais plus logique qu’elle y soit sans les raccourcis

**Comment by ErreipZeyob** [comment]
comme utilisateur naîf je n'aurtais pas pensé spontanément utiliser les touches o/n mais étonnant que cela ne fonctionne pas en cliquant sur les cases à cocher. c'est un peu déroutant. à l'usage ça peut être intéressant

**Comment by Refhi** [comment]
Du coup faut aussi qu'on pense à clarifier que "n" et "o" peuvent servir à ça

**Comment by Refhi** [comment]
probablement à lier avec #186
