### ISSUE TITLE
CB - Patients qui payent plusieurs consultations en 1 fois

### ISSUE THREAD

**Issue by Jitto31** [Refhi/Weda-Helper#212]
Je ne sais pas si techniquement c'est possible ou trop difficile mais pour les cas où les patients consultent en famille et paye tous à la fin, ca serait top d'avoir un bouton sur la FSE qui met paiement par CB mais envoie le paiement en attente au companion pour s'additionner et faire l'envoie au TPE du total à la dernière consultation!

Si trop compliqué, possibilité aussi de créer des favoris de paiement accessible sur le bouton de l'extension?

Merci!

**Comment by Refhi** [comment]
pour le cumul, j'ai peur que ça soit trop complexe
par contre je peux rajouter un champ de saisie dans le bouton de l'extension où l'on puisse taper un montant personnalisé ?

**Comment by Jitto31** [comment]
Oui pas mal le champs de saisie ! Et pourquoi pas un favoris en plus?

**Comment by Jitto31** [comment]
Le favori pour quand ils ont pas la CV et on fait en papier

**Comment by Refhi** [comment]
Pour les règlements manuels j'ai rajouté un lien avec le TPE quand on valide un règlement manuel avec CB de sélectionné
Et j'ai ajouté un champ de saisie manuel dans la popup :)
