### ISSUE TITLE
Créer un défaut TCG - paiement virement 

### ISSUE THREAD

**Issue by Jitto31** [Refhi/Weda-Helper#214]
Autre idée de paiement par défaut 

Quand c'est en sésame sans vital : automatiquement TCG et paiement en virement ?? 

Merci !

**Comment by Refhi** [comment]
My bad !
C'est non documenté mais ça existe déjà...
c'est DéfautTC...

**Comment by Refhi** [comment]
par contre manque le paiement en virement... faut que je creuse...
