### ISSUE TITLE
Problème FSE

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#224]
Problème ancien mais que j'oublie de rapporter depuis un moment: 

Si je vais sur un dossier patient sans carte vitale, que je vais pour faire une FSE, cela me propose bien de faire une TCG ou une dégradée. Par contre quand je clique sur l'un ou l'autre sur la pop cela me récupère l'empreinte vitale du patient précédent dont j'ai lui la carte vitale et non du patient sur lequel je suis en ce moment. Je suis toujours obligé de fermer la pop up et d'aller chercher le paient en cours via l'empreinte.

J'espère que je suis assez clair!

**Comment by Refhi** [comment]
#243 - duplicate

**Comment by ErreipZeyob** [comment]
même soucis avec nouvelle installation sur un nouveau PC alors que cela fonctionne correctement avec mon ancien PC
