### ISSUE TITLE
Formule d'AMC automatique / par défaut 

### ISSUE THREAD

**Issue by OlivierSoussain** [Refhi/Weda-Helper#225]
Bonjour, 

Avec la nouvelle mise à jour Weda helper + la MAJ SCOR de Weda ce matin ça commence à être vraiment bien !
Un grand merci à l'équipe Weda helper. 

Les propositions que j'ai à faire sont désormais du détail. 

Voici celle du jour que je vous soumets : 
Avoir la possibilité de cocher par défaut une formule à appliquer pour les AMC. 
( je dois vous avouer que je n'y comprends pas grand-chose à ces formules, mais en mettant "052 - 100% TM", je suis payé, donc je mets celle-là systématiquement ) 

C'est utile pour les régimes SNCF, CAMIEG, MGEN, on peut faire des TP également sur l'AMC et quand on scan la carte de mutuelle d'un patient. 

![Capture d'écran 2024-08-08 153722](https://github.com/user-attachments/assets/5b117ff8-b07e-4b53-a59c-1d7c23da298c)

**Comment by Refhi** [comment]
De nouveau un système pour se rappeler de la dernière sélection me parait plutôt adapté

Peux-tu me faire quelques captures d'écran pour me montrer comment tu arrives à ce panneau stp ?

**Comment by OlivierSoussain** [comment]
https://github.com/user-attachments/assets/6c697c96-bd95-43af-9291-ce9fc1ccbe78

Voilà un exemple pour une patiente MGEN qui a donc une mutuelle associée à sa Sécurité sociale, les ADRi retrouvent donc sa mutuelle. 
On peut donc ne rien faire payer à la patiente en faisant passer le TP sur AMO et AMC.  Comme pour une CSS ( ex-CMU  ) 
Mais pour la MGEN il y a une petite manipulation à faire pour que l'AMC passe. 
Voici la vidéo. 
Encore une fois il y a plusieurs formules dont je n'y comprends pas grand-chose. 
La "52 - 100 % Ticket Modérateur" semble celle qu'appliquent systématiquement les contrats des mutuelles pour les médecins généralistes. 
Ça ferait donc gagner du temps si on peut cocher systématiquement celle-là ... 

Burn after reading :
Je n'ai pas réussi à anonymiser la vidéo.
Dis-moi quand tu l'as vu et que je peux la supprimer STP.

**Comment by OlivierSoussain** [comment]
![Capture d'écran 2024-10-04 091228](https://github.com/user-attachments/assets/76bdc131-a7ec-463d-88a3-18efb4885583)

Je sais que normalement c'est une idée = un sujet.
Mais là c'est quasiment même problématique ...

J'ai souvent ce pop-up pour les ASS ( ex-CMU ) est-il possible d'avoir une fonction de réponse automatique "oui" ou "non" pour fermer le pop up.

**Comment by Refhi** [comment]
> Je sais que normalement c'est une idée = un sujet. Mais là c'est quasiment même problématique ...
> 
> J'ai souvent ce pop-up pour les ASS ( ex-CMU ) est-il possible d'avoir une fonction de réponse automatique "oui" ou "non" pour fermer le pop up.

Hélas non : ça c'est une popup de VitalZen, donc je ne peux rien faire dessus

Mais la bonne nouvelle c'est que VitalZen n'a probablement plus que quelques mois de vie devant lui, donc bientôt débarrassé de cela également :)

**Comment by Refhi** [comment]
> Etape.pour.mettre.un.TP.sur.partie.complementaire.mp4
> 
> Voilà un exemple pour une patiente MGEN qui a donc une mutuelle associée à sa Sécurité sociale, les ADRi retrouvent donc sa mutuelle. On peut donc ne rien faire payer à la patiente en faisant passer le TP sur AMO et AMC. Comme pour une CSS ( ex-CMU ) Mais pour la MGEN il y a une petite manipulation à faire pour que l'AMC passe. Voici la vidéo. Encore une fois il y a plusieurs formules dont je n'y comprends pas grand-chose. La "52 - 100 % Ticket Modérateur" semble celle qu'appliquent systématiquement les contrats des mutuelles pour les médecins généralistes. Ça ferait donc gagner du temps si on peut cocher systématiquement celle-là ...
> 
> Burn after reading : Je n'ai pas réussi à anonymiser la vidéo. Dis-moi quand tu l'as vu et que je peux la supprimer STP.

Vu ! Merci, tu peux la supprimer.

**Comment by Refhi** [comment]
fait dans la 2.8, tu pourras me dire si ça fonctionne comme attendu quand elle sortira ?
