### ISSUE TITLE
Erreur d'affichage du panel Historique

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#226]
Hello !

Désolé je suis complétement absent du dev en ce moment, je devrais avoir plus de temps à la rentrée.

Juste un soucis avec la dernière version 2.6, l'affichage du panel historique automatique ne fonctionne plus si l'option Z-IMC est activé et que le champ "IMC" n'existe pas (l'exécution de Consultation.js s'arrête et plante à https://github.com/Refhi/Weda-Helper/blob/d74b18689119b08ad4f63827aaae0317433defa1/consultation.js#L431)

**Comment by Refhi** [comment]
Salut Abel, pas de soucis ^^ j'espère que tu te reposes un peu quand même

=> fermé car doublon de #221
