### ISSUE TITLE
Nouveau raccourcis

### ISSUE THREAD

**Issue by Philout14** [Refhi/Weda-Helper#227]
Bonjour,
Un raccourcis pour valider l'importation dans "Vos échanges sécurisés" serait la bienvenue ... ?
Merci d'avance et bon courage !

**Comment by Abeldvlpr** [comment]
Bonjour, le raccourci existe déjà (Alt + V) mais il n’est pas affiché sur le bouton

**Comment by Philout14** [comment]
Désolé, je n'ai pas fait attention, je vais tester !

**Comment by Abeldvlpr** [comment]
On va rajouter le raccourci sur le bouton pour que ce soit plus clair
