### ISSUE TITLE
Affichage historique

### ISSUE THREAD

**Issue by Rewind7596** [Refhi/Weda-Helper#229]
J'ai bien coché la case "consultation" pour "Ouvrir automatiquement l'historique dans dans les pages sélectionnées ci-dessous et l'afficher dans un colonne à gauche." Pourtant, l'historique ne s'affiche plus depuis plus d'une semaine. Cela marche bien quand je fais un courrier par contre.

**Comment by Abeldvlpr** [comment]
Bonjour, c’est un bug qui va être corrigé, en attendant vous pouvez le corriger en créant un champ « IMC » dans les réglages de Weda sur les règles de suivi (TA, FC, poids, taille etc.)

**Comment by Abeldvlpr** [comment]
Fix dans #233
