### ISSUE TITLE
Clic en moins

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#230]
Serait il possible de supprimer ce pop up lors de l'importation de biologies ou le valider automatiquement? Ca sert à rien...

![image](https://github.com/user-attachments/assets/3c213388-09ae-4279-9ca0-470fa7f03b1d)

**Comment by Refhi** [comment]
Malheureusement pas possible :-/

j'avais déjà essayé sur d'autres éléments, mais malgré la suppression de l’attribut onclick de l'élément, le comportement reste le même.
