### ISSUE TITLE
bug inversion ordo ALD

### ISSUE THREAD

**Issue by Jitto31** [Refhi/Weda-Helper#231]
bonjour
suite à l'amélioration du bouton inversion pour les ordo ALD (Top par ailleurs merci beaucoup!!!)
le problème c'est que quand on fait le clic droit sur la souris pour le mettre direct en ALD, l'inversion se fait et les prescription se retrouvent en non ALD ^^ 
Il faudrait annuler l'option quand c'est un clic droit sur la souris et activer l'action que quand c'est un clic gauche!

Merci!

**Comment by DocDomi** [comment]
Oui, le problème est le même quand on renouvelle une demande de laboratoire en ALD avec l'icone : 

![image](https://github.com/user-attachments/assets/c4a85f37-b941-458d-99cd-a2a81944ebc5)

Merci !

**Comment by Refhi** [comment]
Merci pour le rapport de bug, effectivement, je met ça dans une milestone dès que j'ai 5 minutes :)
