### ISSUE TITLE
bug type de prescription ordo numerique

### ISSUE THREAD

**Issue by Jitto31** [Refhi/Weda-Helper#232]
Depuis la dernière mise à jour la classification bug plus souvent

>"Faire pratiquer par orthoptiste" me met pédicurie
>"podologue"= non reconnu
>"Kinésithérapeute DE"= me met orthophonie
>"Infirmière DE" = me met kiné

problème que chez moi?? merci!

**Comment by Abeldvlpr** [comment]
Bonjour, c'est un bug suite à la dernière mise à jour de Weda.
C'est corrigé dans #234 ca devrait sortir bientôt !

**Comment by Jitto31** [comment]
si weda mets des bâtons dans les roues aussi^^merci!

**Comment by Refhi** [comment]
normalement je m'en occupe cet am
