### ISSUE TITLE
fenêtre étiquette au second plan

### ISSUE THREAD

**Issue by rrrrr09** [Refhi/Weda-Helper#240]
Salut
merci beaucoup pour les mises a jour successives depuis le départ
Que d'évolutions et surtout que de confort gagné

petit bug remarqué récemment : dans une consultation si je souhaite attribuer une étiquette la fenêtre s'ouvre mais reste au second plan par rapport aux fenêtres consultation et historique

Encore merci
![Capture d'écran 2024-09-05 102644](https://github.com/user-attachments/assets/0995f37e-559f-4a51-a593-6bdbc4d965c0)

**Comment by DrFloW71** [comment]
Tu m'étonnes! Ce logiciel n'est clairement plus le même avec Helper! On est sorti de l'âge de pierre!

**Comment by Refhi** [comment]
c'est avec plaisir que je ferme ce ticket sans le résoudre :-P

En effet l'affichage de l'historique à gauche passe en natif chez Weda sous quelques semaines ^^

Ils feront quelque chose de bien plus propre que Weda Helper pour ça 😁

(je le rouvrirais bien sûr si ça traîne un peu)
