### ISSUE TITLE
Ordo numériques

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#241]
Salut, depuis la MaJ les ordos num restent bloquées sur le choix du type d'ordo (qui est le bon) mais ça ne valide plus tout seul. 

![image](https://github.com/user-attachments/assets/c8b45703-2a08-45d2-b56c-6a50ed2a8d72)

Console:

Aucune mutation détectée pendant 300ms, je considère la page comme chargée. Appel du Callback. (ajout raccourcis aux iframes)
keyCommands.js:141 [addAllShortcuts] activé
content.js:8 Aucune mutation détectée pendant 1000ms, je considère la page comme chargée. Appel du Callback. (ajout raccourcis aux iframes)
keyCommands.js:141 [addAllShortcuts] activé
content.js:755 Bouton trouvé ! Je le redimentionne, lui ajoute un id et note le raccourcis clavier par défaut <button _ngcontent-cre-c272 mat-raised-button mat-dialog-close title=​"Annuler" class=​"mat-focus-indicator mat-raised-button mat-button-base" type=​"button" id=​"targetAnnuler" style=​"width:​ auto;​">​Annuler (alt+A)​</button>​
content.js:732 ajout de raccourcis au button <button _ngcontent-cre-c272 mat-raised-button mat-dialog-close title=​"Annuler" class=​"mat-focus-indicator mat-raised-button mat-button-base" type=​"button" id=​"targetAnnuler" style=​"width:​ auto;​">​Annuler (alt+A)​</button>​
content.js:755 Bouton trouvé ! Je le redimentionne, lui ajoute un id et note le raccourcis clavier par défaut <button _ngcontent-cre-c272 type=​"submit" mat-raised-button color=​"primary" title=​"Transmettre" class=​"mat-focus-indicator mat-raised-button mat-button-base mat-primary" id=​"targetValider" style=​"width:​ auto;​">​Transmettre (alt+V)​</button>​
content.js:732 ajout de raccourcis au button <button _ngcontent-cre-c272 type=​"submit" mat-raised-button color=​"primary" title=​"Transmettre" class=​"mat-focus-indicator mat-raised-button mat-button-base mat-primary" id=​"targetValider" style=​"width:​ auto;​">​Transmettre (alt+V)​</button>​
prescription.js:376 menu déroulant trouvé, je clique dessus (4) [div.mat-select-trigger.ng-tns-c78-2, div#mat-select-value-1.mat-select-value.ng-tns-c78-2, div.mat-select-arrow-wrapper.ng-tns-c78-2, div.mat-select-arrow.ng-tns-c78-2]
prescription.js:389 Type de soin non détecté, je laisse l'utilisateur sélectionner le bon
metrics.js:41 Metrics updated for 2024-09-05: {clicks: 567, drags: 711, keyStrokes: 275}
metrics.js:41 Metrics updated for 2024-09-05: {clicks: 568, drags: 712, keyStrokes: 275}
content.js:8 Aucune mutation détectée pendant 300ms, je considère la page comme chargée. Appel du Callback. (ajout raccourcis aux iframes)
keyCommands.js:141 [addAllShortcuts] activé
content.js:8 Aucune mutation détectée pendant 1000ms, je considère la page comme chargée. Appel du Callback. (ajout raccourcis aux iframes)

**Comment by Abeldvlpr** [comment]
Oui c'est du à la mise à jour faite par Weda aujourd'hui, je corrige ca dans la soirée !

**Comment by Abeldvlpr** [comment]
Corrigé dans la 2.6.2

**Comment by Refhi** [comment]
Je pousse ça ASAP, merci à tout les deux
