### ISSUE TITLE
Plusieurs consultations créées avec Alt-1

### ISSUE THREAD

**Issue by DocDomi** [Refhi/Weda-Helper#242]
Quand j'utilise Alt-1 ça m'ouvre plusieurs consultations : 2, 3, 4 ou même 5 c'est variable ! Cela le fait depuis la mise à jour de fin juin : 
![image](https://github.com/user-attachments/assets/d62d0b1c-c340-4811-9ec7-dbc8aab60760)

Je n'ai pas réussi à comprendre pourquoi le nombre de ces consultations est variable.
Cela vient peut-être du fait que j'ai toujours plusieurs onglets ouverts pour le patient en question ? 
Si cela peut t'aider, concrètement, j'ai donc plusieurs onglets ouverts pour un patient, quand je reçois le patient suivant, je mets la carte vitale et tous les onglets en question lisent automatiquement la carte et ouvrent automatiquement le dossier du patient. (C'est très pratique).

Merci !

**Comment by Abeldvlpr** [comment]
Bonjour,

C'est en effet du au fait que vous avez plusieurs onglets ouverts. L'utilisation du raccourcis déclenche une nouvelle consultaiton sur chacun des onglets.

@Refhi On pourrais rajouter un check pour n'appliquer le raccourcis que sur la page active ?

**Comment by DocDomi** [comment]
Une nouvelle consultation ne s'ouvre que sur l'onglet actif, c'est quand je la ferme que je constate qu'il existe d'autres consultations vides.

Ce problème n'était pas présent avant la mise à jour de fin juin (je faisais exactement pareil avec les onglets).

**Comment by Refhi** [comment]
tentative de fix avec https://github.com/Refhi/Weda-Helper/commit/b6b37f34baaf0debabc54232f8b2ceae98e699d1
si y'en a qui veulent tester en attendant la release :)

**Comment by DocDomi** [comment]
Bon, après une journée de test de la version 2.6.3, voici mon feed-back.

Avec la version précédente et l'utilisation de Alt-1 j'avais parfois jusqu'à 6 consultations créées. Avec la version 2.6.3 j'en ai eu en général simplement 2... Ca reste 1 de trop ;-) 

Merci encore pour le travail fourni !

**Comment by Refhi** [comment]
Je pré-release la 2.7 qui règle enfin le problème tout à l'heure
mais j'attends la validation de l'équipe de test de Weda avant publication :)

**Comment by Refhi** [comment]
@DocDomi 
est-ce que tu pourrais tester https://github.com/Refhi/Weda-Helper/releases/tag/v2.7-RC4 stp ?
