### ISSUE TITLE
Problème pour FSE dégradées et FSE téléconsultation

### ISSUE THREAD

**Issue by DocDomi** [Refhi/Weda-Helper#243]
Quand je veux faire une FSE dégradée ou FSE téléconsultation et que je clique sur la zone correspondante ici : 
![image](https://github.com/user-attachments/assets/3a4080f4-9af6-4934-bf9f-dea5c0387036)
immanquablement cela sélectionne les données, non pas du patient en cours correspondant au dossier ouvert mais du patient précédent.

Cela se produit depuis que j'utilise Weda Helper (ce n'est pas lié aux dernières mises à jour).

Merci !

**Comment by DrFloW71** [comment]
IDEM chez moi je crois que j'ai déjà fait un ticket. Merci de ton retour.

**Comment by Abeldvlpr** [comment]
Bonjour,

J'ai récement changé d'installation et j'ai également ce problème qui est apparu alors qu'il n'était pas présent auparavant.. Je jete un coup d'oeil à l'ocasion

**Comment by ErreipZeyob** [comment]
désolé même problème pour moi : selection du patient précédent à chaque dégradé ou téléconsultation depuis 2-3 semaines

**Comment by ErreipZeyob** [comment]
J'ai tout desinstallé : Weda compagnon et Weda Helper : donc le probleme vient de WEDA

**Comment by Refhi** [comment]
Merci pour les tests et le retour dédouanant WH, ça nous évite pas mal de boulot !

Je cloture le ticket, et on attend patiemment mi-2025 pour la disparition de vitalzen !
