### ISSUE TITLE
bug click droit pour prescription en ALD

### ISSUE THREAD

**Issue by ErreipZeyob** [Refhi/Weda-Helper#258]
depuis peu le click droit qui premet de pescrire des radio ou biolo en ALD dysfonctionne
L'ordonnance est bien créée en bizone mais les prescriptions sont envoyées dans la partie basse de la bizoner hors ALD

**Comment by Refhi** [comment]
Oui, le bug sera corrigé dans la 2.7 qui est en attente de validation.
Compte quelques jours 🤞

Duplicate #231
