### ISSUE TITLE
impression automatique AT bloquée

### ISSUE THREAD

**Issue by ErreipZeyob** [Refhi/Weda-Helper#259]
Bonjour
l'automatisation la réalisation des arrêts de travail ne se fait plus pour une raison inexpliquée (pourtant la case dans les options de WEDA est toujours bien cochée)

<img width="494" alt="image" src="https://github.com/user-attachments/assets/a40100bb-c4ef-4b6f-b63b-c75921e1c938">

**Comment by Refhi** [comment]
Merci pour le ticket

Je t'invite à voir #246
