### ISSUE TITLE
Passer les impressions en fond de tâche

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#263]
Actuellement l'impression ordo numérique + DMP prend 10+ secondes.

L'idée serait dès le lancement de l'impression d'ouvrir un nouvel onglet sur l'accueil du patient, et de fermer l'onglet initial une fois l'impression terminée.

**Comment by DrFloW71** [comment]
Hâte d'essayer ça! C'est une super idée!

**Comment by Refhi** [comment]
Problématique : 
- lorsqu'un onglet se ferme suite à une impression alors qu'une FSE est en cours, cela bloque le lien avec vital zen

Solution à implémenter : 
- temporiser la fermeture tant qu'un onglet FSE est ouvert.

**Comment by Refhi** [comment]
fait, à tester.
