### ISSUE TITLE
Volet latéral défaillant

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#264]
A l'aide depuis cette AM l'historique n'apparait plus automatiquement sur le volet G. En cliquant sur historique il se remet à G mais avec une présentation différente (volet plus large, menus mal positionnés)! A tout les coup WEDA à bidouillé un truc qui impacte le hack de Hervé!

![image](https://github.com/user-attachments/assets/88940af6-6b49-4923-bf4f-b15e4c05d3f4)

**Comment by Refhi** [comment]
Ah, en effet, c'est le début de la reprise des fonctions de WH par Weda !

On a mis en place un système qui permet de désactiver les fonctions de WH quand Weda les implémente à la place.

Là j'ai quelques points à rattraper, notamment de permettre l'ouverture automatique de cet historique (simple à faire, ça va pas tarder) et de réactiver l'historique à gauche sur les autres pages (genre Certificat, y'a un truc à déboguer)

**Comment by Refhi** [comment]
https://github.com/Refhi/Weda-Helper/commit/83511760f594cfde7744812bf2a04f8b0e0cce9c

normalement c'est réglé (sauf pour la taille de l'historique, c'est un choix de Weda, je risque d'avoir du mal à y toucher, dis-moi ce que tu en penses)

**Comment by Philout14** [comment]
Inutile en double écran 👯
