### ISSUE TITLE
Bug touche Tab

### ISSUE THREAD

**Issue by Philout14** [Refhi/Weda-Helper#265]
Bonjour, depuis ce matin, la touche Tab ne permet pas de changer de section dans l'observation.
Après désactivation de Weda Helper, ça refonctionne (moyenne 3 pressions sur Tab pour changer d'élément comme poids, taille etc...)
Bon courage

**Comment by Refhi** [comment]
est-ce que tu peux me confirmer que le bug se manifeste quand il s'agit de changer de champ d'items (poids/taille/etc.) et/ou de champ de saisie de texte (Histoire de la maladie, examen clinique, etc.) ?
Merci :)

**Comment by Philout14** [comment]
Je te le confirme ! Désolé si mon explication n’était pas claire

**Comment by Refhi** [comment]
euh les deux du coup ? ^^

**Comment by Philout14** [comment]
Désolé j'ai lu en diagonale : ça ne concerne que les variables (poids, taille, etc...). Le changement de fenetre "interrogatoire", "examen clinique" semble fonctionner (mais ça n'a jamais bien fonctionné chez moi : ça change une fois d'encadré au premier appui sur tab, mais ça ne fonctionne pas après...)

**Comment by Adrien-Pey** [comment]
Bonjour,
J'ai remarqué ce bug. Si je clique sur "utiliser le suivi défini dans mes préférences" puis sur "utiliser le suivi pour les patients", la tabulation reprend le comportement attendu (mais je perd les unités de suivi et c'est uniquement tant que cette fenêtre de consultation est ouverte). Et il m'a semblé que si c'est un nouveau patient, avec les valeurs de suivi par défaut, le comportement de la tabulation était celui attendu pour les variables de suivi.

**Comment by Refhi** [comment]
Merci @Adrien-Pey ça va faciliter la traque du bug

**Comment by Refhi** [comment]
Bizarre je n'arrive pas à reproduire le bug.
J'aurais besoin de plus d'éléménts @Philout14  et @Adrien-Pey : 
- vous êtes sous MAC ? Windows ? Quel navigateur ?
- est-ce que vous pouvez faire une capture d'écran, console ouverte, au moment où le bug se produit, et quand il se résoud avec votre manip ?
Pour ouvrir la console :
![image](https://github.com/user-attachments/assets/a6f76e21-303b-4fdd-9364-985e43f6244f)
Dans l'idéal il me faudrait quelque chose comme ça : 

![image](https://github.com/user-attachments/assets/1360d9fc-e67a-4b2b-85be-107225fa1ef4)

Merci :)

**Comment by Adrien-Pey** [comment]
Alors Je suis sur windows 10 et chromium. Ce bug est aléatoire et semble relié à un autre bug. En fait à l'ouverture de la consultation, l'historique latéral ne s'ouvre pas. C'est comme si weda helper ne prenait pas la main et là il y a le bug dans la tabulation. Quelques fois il y a un délai de quelque seconde avant l'ouverture de l'historique latéral et durant ce délai la tabulation n'est pas conforme puis devient conforme. La manip de cliquer sur "utiliser le suivi défini xxx" semble permettre à weda helper de reprendre la main puisqu'il s'affiche alors l'historique latéral.

![Capture1](https://github.com/user-attachments/assets/6d6b5237-33ee-4c94-aa94-2d34c48e32ba)

![Capture2 sans bug](https://github.com/user-attachments/assets/60a44b98-4dbb-463b-963e-0ab9fb5fc7e2)

**Comment by Refhi** [comment]
super, ça aide.

Je vois aussi que tu as un thème custom, je vais regarder si ça n'est pas là le problème.

Pour les screenshot, peux-tu recommander mais en sélectionnant "console" en haut à droite stp ?

Merci :)

**Comment by Adrien-Pey** [comment]
Ok. J'ai fait plusieurs screen, je ne sais pas trop le moment ou ça bugue. Je pense que c'est plutôt sur le début alors je suis remonté un peu sur la console. 
Si tu n'arrives pas à reproduire le bug, une prise de contrôle à distance peut s'envisager. 
J'ai entendu dans une formation sur weda aujourd'hui que l'historique latéral était passé en natif sur weda.

![Capture1](https://github.com/user-attachments/assets/ca967294-127a-4807-bb38-9c073ee5d564)
![Capture2 sans bug](https://github.com/user-attachments/assets/7ed8182c-22b9-4f8c-9ed4-5198c706a8d5)
![console 1](https://github.com/user-attachments/assets/ec5e9333-b41f-40f4-9724-011dffc26cf4)
![console2](https://github.com/user-attachments/assets/24d5c462-0743-4bd3-8ade-c439826422f5)
![console3](https://github.com/user-attachments/assets/6902aa64-f865-4d86-9961-34c7b148fc39)

**Comment by Refhi** [comment]
Merci pour les retours !

J'ai pu reproduire le bug, au moins en partie, je pense avoir pu le corriger dans la 2.8 (qui sortira dans 1-2 semaines), si tu es à l'aise, tu peux la tester ici https://github.com/Refhi/Weda-Helper/archive/2eb72cc6cc29827ab27da08f87bd9f980bd99c2a.zip , (chrome => extension => mode développeur => charger extension non empaquetée) => juste n'oublie pas de la retirer après test, sous peine de ne plus recevoir les MAJ de WH

N'hésite pas à me tenir au courant ^

P.S. Pour l'historique gauche, oui, Weda est en train de l'intégrer, on a pas mal échangé, et ils sont en train d'affiner le truc :)

**Comment by Refhi** [comment]
@Adrien-Pey et @Philout14 est-ce que vous avez reçu WH 2.8 ?

Si oui est-ce que le problème est corrigé ?

**Comment by Philout14** [comment]
Bonsoir,
Oui c’est bon pour moi !
Merci beaucoup !

Philippe
