### ISSUE TITLE
Implémenter dans la fonction "Ouvrir automatiquement l'historique ..."  la fonction "uniquement les titres "

### ISSUE THREAD

**Issue by Dr-Vaucel** [Refhi/Weda-Helper#268]
Bonjour,

Actuellement la fonction "Ouvrir automatiquement l'historique dans dans les pages sélectionnées ci-dessous et l'afficher dans un colonne à gauche." permet d'afficher  Consultation,  Certificat,  Demande,  Courrier (beta),  Formulaire... au choix

Ce qui nous donne un affichage comme ca : 
![{D2880528-4E59-444F-A052-E262FC69D09F}](https://github.com/user-attachments/assets/df35c7b1-93db-4f19-ac5b-cd6aa6ca7def)

Est ce qu'il serait possible d'avoir l'affichage que des titres avec un "clic" automatique sur la case tout filtré pour avoir un affichage comme cela ?
![{C20C2DD4-D1FA-4DE2-9A7C-5357A10FB8EA}](https://github.com/user-attachments/assets/9fb46a99-891f-412c-9feb-b6414fa59ce0)

Je pense que cela faciliterai ma pratique

Merci par avance,

Dr Vaucel

**Comment by Refhi** [comment]
Merci pour la suggestion,
je regarde ça à l'occasion

**Comment by Refhi** [comment]
Fait pour la 2.8
