### ISSUE TITLE
Cocher automatiquement "inclure la FSP en SCOR" lors de la réalisation d'une FSE dégradée

### ISSUE THREAD

**Issue by klmmc** [Refhi/Weda-Helper#271]
Youpi, Weda permet enfin le SCOR pour ne plus envoyer les feuilles de soin papier! On pourrait même s'épargner un clic en cochant automatiquement "joindre la FSP en SCOR" lorsqu'on fait un dégradé, je ne sais pas si c'est implémentable 
Merci pour votre boulot!

**Comment by Refhi** [comment]
c'est censé l'être, mais ça ne fonctionne pas encore bien, je m'en occupe quand j'ai 5 minutes :)

**Comment by Refhi** [comment]
Bizarre sur mon 2e pc ça reste coché en permanence.
Je teste au cabinet demain.

**Comment by Refhi** [comment]
Finalement pu reproduire le problème, fonction implémentée :)
