### ISSUE TITLE
Automatiser l'envoi avec l'impression et l'envoi au DMP pour un courrier 

### ISSUE THREAD

**Issue by klmmc** [Refhi/Weda-Helper#272]
Dans l'idéal, il faudrait pouvoir avec un seul raccourdi automatiser : 
- Cocher le médecin traitant dans les destinataires du courrier
- Envoyer le courrier via MS Santé (cf capture d'écran)
- Impression papier via le premier modèle
- Envoi au DMP
Il me semble qu'avec Ctrl P ça imprime mais n'envoie pas au DMP, même si la case "envoyer sur le DPM dès l'impression" est cochée. 
![image](https://github.com/user-attachments/assets/388660aa-3fc4-47fe-a677-da4a28684569)
![image](https://github.com/user-attachments/assets/ff054a4b-2bd8-4030-8f39-d75629c38fb1)

Merci

**Comment by Dr-Vaucel** [comment]
Sinon la demande est que à l'ouverte du courrier au lieu d'avoir :
![{90322A50-1B7A-47A1-A3D1-DD74E01FAEDF}](https://github.com/user-attachments/assets/f8630b61-704e-474d-912b-d0c5c93effef)

on ai :
![{527CA402-E154-4A14-BAEA-7676F710AD9D}](https://github.com/user-attachments/assets/a783dfab-f78c-48db-873f-75fc9636c1ab)

PS : pour le secret médical c'est mon dossier perso donc pas de souci ;)

**Comment by Refhi** [comment]
pour la phase 1 : #275
pour la phase 2 : #274 
pour la phase 3 : Ctrl+P mais attention à ne pas activer instantPrint. Si le Companion est installé, il faudra sélectionner "Fermer la fenêtre de prévisualisation" dans les options.

Donc le flow sera : ctrl+P, puis ctrl+E quelques secondes après.

=> si tu veux bien je t'invite à attendre la 2.9, puis à me dire si ça correspond à ton usage, ou si tu veux qu'on voit pour pousser plus loin l’enchaînement 1 => 2 => 3 jusqu'au bout (mais ça va être + complexe à développer >.< )
