### ISSUE TITLE
Ajouter un raccourcie pour envoyer directement un courrier

### ISSUE THREAD

**Issue by Dr-Vaucel** [Refhi/Weda-Helper#274]
Bonjour Hervé, bonjour à tous,

Serait-il possible d'ajouter un raccourcie pour envoyer directement un courrier ?
Un raccourci dans l'esprit CTRL+P ou CTRL+SHIFT+P
![{3E9CF206-3A2C-4F62-8CEA-821ADE25E6FD}](https://github.com/user-attachments/assets/75875a73-876b-493e-9d4e-26b7bd032722)

Merci par avance,

Dr Vaucel

**Comment by Refhi** [comment]
Oui c'est assez simple à faire.
Pour l'instant Ctrl+D/P utilise Shift pour accéder au 2e modèle.
Peut-être Alt+E ?

**Comment by Refhi** [comment]
en lien avec #272

**Comment by Dr-Vaucel** [comment]
Bonjour Refhi

Certain comme moi on des modèles avec des tableau (oui c'est une idée de merde) (1)
du coup CRTL+SHIFT + D/P imprime en version tableau (2)
Bon et comme l'impression en version tableau je me suis démerdé sans je viens de le supprimer 
je viens de refaire le test avec un courrier sans avoir de deuxième modère (3) u coup CRTL+SHIFT + D/P ne fait rien 

>>> Je pense qu'une fonction CTRL+ E (Envoyer serai idéal)

---------------------------------------------------------------------------------------------

AVEC DEUX MODELE 
image choix impression courrier (1) 
![{E798821E-2C8B-4684-A9F8-C90B2990437C}](https://github.com/user-attachments/assets/85c6ac94-2149-43e3-a2fa-f8558bf9ea10)

Courrier : CRTL+ D/P
![{0EC10B84-F8B6-4543-87EB-240B4B4BF4C4}](https://github.com/user-attachments/assets/8dd80a3f-37b1-4cb4-bee7-692d2a3d2acf)
(Merci grace a toi j'ai vu qu'un de mes associé à fait de la merde avec la mise en page)

ou Tableau (2) CRTL+SHIFT + D/P
![{A14C02D3-1F9A-4A3F-9CE5-9B79C954C7E9}](https://github.com/user-attachments/assets/b43c3543-41d3-47ab-b1cc-0a4495fbda79)

AVEC UN SEUL MODELE 
image choix impression courrier (3) 
![{3F4A60ED-9CD5-49FE-AFDC-33700B36A69C}](https://github.com/user-attachments/assets/6ee5a121-721b-4aab-a6ab-83b9e2ba4e73)

 CRTL+ D/P ne fait rien = imprime ou enregistre
 CRTL+SHIFT + D/P = ne fait rien
------------------------------------------------------------------------------
