### ISSUE TITLE
Bug changement touche des raccourcis

### ISSUE THREAD

**Issue by Dr-Vaucel** [Refhi/Weda-Helper#276]
**Décrivez le bug**
Bonjour, 
il semblerait qu'il soit possible de changer les raccourcis clavier dans la partie option. Soit j'y arrive pas, soit il y a un truc qui dysfonctionne.

**Comment le reproduire**
Pour changer les raccourcis je vais dans Weda Helper  > option (1) > liste des raccoucris 
Puis quand je clique sur un des raccourcis il s'affiche en bleu (2) et c'est tout. Pas de possibilité de taper la comande dans une boite de texte et tout essaye de faire directement un code en tappant sur le clavier (ex CTRL+P) ouvre la commande Windows si elle existe sinon cela ne fait rien
J'ai essayé pour plusieurs raccourcis, il ne peuvent pas être décoché (3) 

auriez vous une solution ? 

**au besoin une capture d'écran (Maj+Win+S)**
(1)
![{75877DDD-D7A9-4BE8-BC24-4E5885E8DD90}](https://github.com/user-attachments/assets/c1fd31d4-ba92-47dd-ad10-8412c4b892f1)

(2)
![{E75C3E96-19A2-45EF-92C2-936F4DEA02B6}](https://github.com/user-attachments/assets/7210f193-a6d8-4b6e-b6f4-895052b2e666)

(3)
![{993D04E1-D8A6-4E1B-8489-54D7B8667C9E}](https://github.com/user-attachments/assets/32eacf81-cd31-47ca-9fe5-4df85fc66794)

(2)

**votre système ! **
 - OS: windows 11
 - Navigateur web chrome

**Comment by DrFloW71** [comment]
Salut, il fallait aller dans les options d'extensions de Chrome. mais effectivement je ne vois plus la possibilité de changer les raccourcis. 
![image](https://github.com/user-attachments/assets/e3a9b3e2-a77f-4228-a049-fe0203c56976)
![image](https://github.com/user-attachments/assets/6cdb7d91-1b85-4816-882f-4ff5e964a968)

**Comment by Dr-Vaucel** [comment]
ok, je l'ai plus non plus dans ce cas

**Comment by Refhi** [comment]
Mmmm... c'est vrai qu'on pourrait rendre l'interface plus claire.

Quand tu cliques sur un des boutons verts, il le passe en bleu, et à ce moment tu es censé faire le nouveau raccourcis sur ton clavier, qu'il t'affiche alors.

Ensuite clique sur Enregistrer pour valider tout ça.

Peux-tu me confirmer que ça fonctionne ?

**Comment by Dr-Vaucel** [comment]
Bonjour,

non ca ne marche pas .

test CRTL + P , clic (passe bleu), fait CTRL+M (pas de modif d'affichage) , puis enregistrer 
![image](https://github.com/user-attachments/assets/22914992-b811-4ae6-a218-eb3a9a5e4177)

test CTRL+M dans weda : ne marche pas ,
Actualisation de Weda helper pas de prise en compte : 
![image](https://github.com/user-attachments/assets/f60cde6d-5a3a-426a-bd7f-6e35206aae59)


est ce que tu as besoin d'autre informations ?

**Comment by DrFloW71** [comment]
Je confirme, testé sur plusieurs PC et ne fonctionnel pas. Donc en l'état plus moyen de changer les raccourcis.

**Comment by Refhi** [comment]
merci à tout les deux, je m'en occupe à l'occasion :)
