### ISSUE TITLE
Ajout fonction Scan

### ISSUE THREAD

**Issue by Dr-Vaucel** [Refhi/Weda-Helper#277]
**Décrivez le bug**
Bonjour,
Est-ce qu'il serait possible d'avoir un raccourci pour faire un scan en utilisant soit le scan primaire soit le scan secondaire .
Car il y a des gens (mes secrétaires, et possiblement moi bientôt) qui ont un scanner d'une imprimante plateau qui ne fait que recto et un scanner recto verso avec chargeur. Du coup avoir une fonction avec un raccourci pour le scan primaire et le scan secondaire .

**Comment le reproduire**
pas réellement de bug

**au besoin une capture d'écran (Maj+Win+S)**
![{81EDD4AF-AA4E-406A-AC33-77F0F0E3892E}](https://github.com/user-attachments/assets/5881ba11-93be-4c04-a8e4-234d97258faa)

**votre système ! (IMPORTANT)**
 - OS: windows 11, 
 - Navigateur web :. chrome,

**Comment by Refhi** [comment]
ça malheureusement pas possible, j'ai déjà essayé :-/ cf. #50
