### ISSUE TITLE
Création DéfautTCALD ? car le DéfautTC ne fonctionne pas automatiquement en téléconsultation avec ALD

### ISSUE THREAD

**Issue by Dr-Vaucel** [Refhi/Weda-Helper#278]
**Décrivez le bug**
bonjour hervé,
Lors de la création d'une téléconsultation pour un ALD la cotation met le DéfautALD et pas le DéfautTC.
Je ne sais pas si cela peut-être corrigé pour que le DéfautTC se mettent pour ALD et non ALD ou s'il vaut mieux faire 2 cotations.

**Comment le reproduire**
Se mettre sur un dossier patient
Choisir dans la facturation téléconsultation 
Puis le choix 
-  ALD = non induit la cotation DéfautTC
- ALD = oui induit la cotation DéfautALD et pas DéfautTC qui ne peut pas toujours être coté en téléconsultation

**au besoin une capture d'écran (Maj+Win+S)**
1 : patient en téléconsultation
![image](https://github.com/user-attachments/assets/57662960-d757-4791-aa02-c9d36990b906)

2 : choix non ALD (= DéfautTC)
![image](https://github.com/user-attachments/assets/a868ad06-4d25-44b8-8342-96d7bfa2be46)

3 : choix ALD (=DéfautALD) et pas DéfautTC
![image](https://github.com/user-attachments/assets/f80a7c03-b732-4327-8629-30b1af50b39e)

**votre système ! (IMPORTANT)**
 - OS: windows 11
 - Navigateur web  chrome

PS : pas de souci de secret médical c'est mon dossier patient pour l'exemple

**Comment by Refhi** [comment]
ça c'est simple, il faut simplement que je remonte le DéfautTC en haut dans les priorités
