### ISSUE TITLE
2 clics à gagner

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#281]
Salut Hervé, petites trouvailles du jour, 2 clics à gagner au niveau des FSE:

![image](https://github.com/user-attachments/assets/75c8baff-f132-42c0-bb73-b3104b09a983)

![image](https://github.com/user-attachments/assets/21643d12-c60a-4830-b0a1-617042d99485)

Merci!

**Comment by Refhi** [comment]
#271 pour le point 2

ok pour le point 1 :)
