### ISSUE TITLE
Ajout d'une case "Consentement à la conultation de l'ordonnance numérique"

### ISSUE THREAD

**Issue by DocDomi** [Refhi/Weda-Helper#282]
Perso, le problème que j'ai est le suivant : la plupart de mes patients consentent à la consultation de l'ordonnance numérique, donc je suis content d'avoir le consentement coché par défaut, ce qui me permet de faire ctrl+P pour lancer l'impression et l'envoi dans le DMP.

Mais j'ai quelques patients qui ne consentent pas. Pour eux, je suis obligé d'aller dans les options de Weda Helper, de décocher la case en question pour pouvoir répondre "non" à la question lors de l'impression, puis de revenir dans les options de Weda Helper, de recocher la case pour les patients suivants.

 

Une solution serait que dans le module prescription, à côté (ou en dessous) de la case "Ordonnance numérique", il y ait "Consentement"  avec "oui" coché par défaut. Pour les patients qui ne consentent pas, il suffirait de cocher "non" avant de faire ctrl+P sans avoir besoin d'aller dans les options de Weda Helper.

Pour ceux qui comme Jules-Antoine préfèrerait que ce soit "non" qui soit coché par défaut, une option de Weda Helper pourrait permettre de choisir ?

Merci !

**Comment by Refhi** [comment]
bonne idée, je m'en occupe à l'occasion

**Comment by Refhi** [comment]
Fait.

Dans l'idée le survol de "Ordonnance numérique" permet d'afficher un choix Oui/Non.

Ça rajoute un clic, mais je vois pas trop comment faire autrement :-/

**Comment by DocDomi** [comment]
Ça m'a l'air très bien ! Merci !

Dominique GAUTHIER
________________________________
