### ISSUE TITLE
Bug affichage historique dans Paramédical

### ISSUE THREAD

**Issue by Dr-Vaucel** [Refhi/Weda-Helper#283]
Bonjour,

Je ne sais pas si je suis le seul mais j'ai un bug d'affichage dans les demande uniquement pour le "paramédical" ou la fenêtre centrale se superpose avec la barre latérale droite.
Je tenais à le faire remonter

voir ci dessous

![image](https://github.com/user-attachments/assets/dae94f76-484b-4034-bf7f-65aee2d714d3)
![image](https://github.com/user-attachments/assets/0ec7a197-6c96-4147-a360-7bfba550f804)
![image](https://github.com/user-attachments/assets/c2ae2886-0e66-4833-83a0-11890ecd6fb2)

**Comment by Refhi** [comment]
ah. C'est lié à la taille des titres dans tes demandes "Paramédical" (ça élargis la colonne)

Si c'est possible je t'invite juste à les raccourcir => ces modifs sont sinon très fastidieuses à faire de mon côté :-/

Tiens-moi au courant si ça ne suffit pas :)
