### ISSUE TITLE
Conflit du raccourci Ctrl+U 

### ISSUE THREAD

**Issue by jeandw** [Refhi/Weda-Helper#286]
Tout d'abord énorme merci pour cet énorme boulot déjà accompli ! 

Le raccourci Ctrl+U utilisé pour uploader un fichier interfère avec le raccourci natif WEDA servant à souligner le texte, 

Existe-t-il un moyen pour désactiver ce raccourci ? 

Merci beaucoup 

- sur Win 11 pro / Chrome Version 131.0.6778.86 (Build officiel) (64 bits)

**Comment by DrFloW71** [comment]
Tu peux personnaliser les raccourcis, il te suffit de changer le raccourcis dans les options de WH ;)

**Comment by jeandw** [comment]
Le click est sensé ouvrir une popup ? chez moi rien ne se passe, ça change juste le bouton en bleu

![image](https://github.com/user-attachments/assets/6531dcae-4ab4-4c47-a237-8423072559d0)

**Comment by Abeldvlpr** [comment]
Bonjour,

Une fois que le bouton est bleu vous pouvez saisir le raccourci que vous voulez pour remplacer Ctrl+U.

Pensez à enregistrer les options une fois que vous l’avez modifié

**Comment by jeandw** [comment]
Ca ne marche pas chez moi, et j'ai ce bug 
![image](https://github.com/user-attachments/assets/354399c1-4db1-4c60-bfe8-d19f279384c2)

**Comment by Refhi** [comment]
ah oui, désolé c'est un bug qui va être réglé en 2.8
(fin de semaine normalement)

**Comment by Dr-Vaucel** [comment]
Bug réglé ce jour, tu peux de nouveau changer les raccourcis ;)
