### ISSUE TITLE
Idée: impression auto pour les AM comme pour les prescription

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#294]
Avec ouverture d'un nouvel onglet comme pour les prescription?

**Comment by Refhi** [comment]
merci pour la suggestion :)

mais plutôt pas pour l'instant :
- l'instantPrint est fastidieux à implémenter, et les AM ne représentent qu'une petite part des impressions quotidiennes
- il faut de toute façon manuellement fermer la fenêtre de prévisu
=> peut-être à relancer si Weda change à nouveau la prévisu des AM
