### ISSUE TITLE
Pb affichage atcd auto + gauche ?

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#295]

**Comment by joellebatot** [comment]
Hello c'était moi qui avais soulevé le pb, merci d'avoir déjà ouvert le sujet (j'ai un peu de retard...)
--> dans le module consultation les ATCD ne s'ouvrent JAMAIS systématiquement malgré cochage OK de la case dans les options :
![atcd](https://github.com/user-attachments/assets/c55f541e-ed10-449d-abb0-1b3ecf935f3f)

Je suis obligée d'aller cliquer dessus pour les voir . Pourtant il me semble qu'à un moment ça fonctionnait..
