### ISSUE TITLE
Valider les bio avec Alt+V

### ISSUE THREAD

**Issue by Dr-Vaucel** [Refhi/Weda-Helper#296]
**Décrivez le bug**
Est ce qu'il serait possible de valider les bio avec alt + v pour cliquer sur la touche "affecter ce resultat" ?

**au besoin une capture d'écran (Maj+Win+S)**
![{497912EF-000C-439F-B714-0B2048150D98}](https://github.com/user-attachments/assets/4282e21f-bf0a-46d1-b865-222f89e7b296)

**votre système**
 - OS: windows 11,
 - Navigateur web chrome

**Comment by Dr-Vaucel** [comment]
et valider ce pop up aussi

![{8E39B1A6-E134-4766-8D38-2829FEEDC0AA}](https://github.com/user-attachments/assets/6f27e293-f417-479e-aca6-e5a0e4edc1dc)

**Comment by Abeldvlpr** [comment]
Bonne idée pour valider la biologie, on le rajoute dans la prochaine version
Pour ce qui est de l'association à un résultat ca peut s'envisager de cliquer automatiquement sur annuler sous la forme d'une option

**Comment by Abeldvlpr** [comment]
Implémenté pour la première partie
Il reste l'ajout d'une option pour cliquer automatiquement sur annuler

**Comment by Refhi** [comment]
J'aime bien l'idée !

Pour la fenêtre d'association je ne l'ai jamais vue 🤔 c'est à quel endroit ?

**Comment by Abeldvlpr** [comment]
Je viens de voir que c’était une option à cocher dans Weda directement déjà !
Case « Lié à une demande » sur la page HPRIM, si vous la décochez ça arrêtera de vous demander de l’associer à une prescription

**Comment by Dr-Vaucel** [comment]
Merci pour l'aspect "lier une demande". 
J'ai cherché longtemps dans les paramètres. 
J'avais pas vu ca. 
Merci

![image](https://github.com/user-attachments/assets/2968b63a-be56-4127-9e54-348b822ed193)

**Comment by Refhi** [comment]
ça a l'air d'être ok de mon côté, je clôture pour l'instant
