### ISSUE TITLE
Fiche memo non disponible. Erreur 404

### ISSUE THREAD

**Issue by Solus-rgb** [Refhi/Weda-Helper#297]
**Décrivez le bug**
Merci de décrire succinctement le bug ex. "les tabulations en consultation ne fonctionnent pas".

**Comment le reproduire**
Décrivez-moi les étapes pour reproduire le bug

**au besoin une capture d'écran (Maj+Win+S)**
Pensez à masquer les noms/prénom

**votre système**
 - OS: [e.g. iOS, mac, windows 11, etc.]
 - Navigateur web [e.g. chrome, safari, firefox]

**Comment by Refhi** [comment]
ah oui, faut qu'on pense à supprimer les liens :-/
En pratique la fiche memo avait vocation à être remplacée par l'appuis long sur "Alt"
est-ce que ça répond à ta problématique, ou veux-tu qu'on en refasse une ?

**Comment by Solus-rgb** [comment]
Merci pour votre réponse si rapide.
J'ai essayé d'appuyer sur le ALT " mac" c a d option, mais rien ne se
passe. Est ce que cela est sur une autre touche sur Mac ?

Merci

Docteur Marine Le Duc-Solus
www.leduc-solus.com
Tel : 01 47 22 98 61
mobile: 06 18 07 83 82

**Comment by Abeldvlpr** [comment]
Bonjour,

C'est un bug sur Mac, la touche Alt n'est pas prise en compte correctement, je regarde ca pour la prochaine version !

**Comment by Abeldvlpr** [comment]
@Refhi Je viens de regarder ton implémentation pour le tooltip avec le maintien du Alt, ca n'a pas l'air de fonctionner sur mac. J'ai pas de Windows sous la main pour tester mais est-ce que tu peux me confirmer que l'event keydown trigger à répétition sur Windows lorsque l'on maintient la touche appuyée ? Sur mac ca ne le trigger qu'une fois du coup l'implémentation ne fonctionne pas...

**Comment by Refhi** [comment]
ah oui en effet, c'est comme ça que WH le détecte sous windows...
sous mac en attendant tu peux spammer manuellement alt, et ça doit fonctionner.
Faut qu'on fix ça du coup...

**Comment by Abeldvlpr** [comment]
Ouais mais du coup en le spammant ça trigger checkAltRelease donc ça s’affiche et ça disparaît instantanément..
Je pense qu’on peut le réimpriment et avec un évent keydown et keyup et un timer entre les deux. J’attends de recevoir mon PC pour le cabinet et je m’en occupe si tu veux

**Comment by Solus-rgb** [comment]
En fait, mon fils fait des études de computer Science  aux États-Unis, et
comme je ne comprenais pas du tout vos échanges, je lui ai transféré pour
qu’il  m’explique en français !. Et du coup il s’est amusé à développer
cette fonctionnalité. Ça l’amuse beaucoup. donc si vous avez envie d’être
aidé, je pense que ça lui fera plaisir

Dr Marine Le Duc-solus www. leduc-solus.com

**Comment by Refhi** [comment]
@Solus-rgb Super :)

Je ne m'attendais pas à voir un non-médecin participer ^^ 

Je lui laisse un message sur #300 s'il veut me contacter ça serait super :)
