### ISSUE TITLE
erreur d'impression de l'arret de travail

### ISSUE THREAD

**Issue by dr-ranooo** [Refhi/Weda-Helper#299]
l'impression automatique de l'arret de travail fonctionne mais il imprime le volet employeur vierge

**Comment by Refhi** [comment]
pas de nouvelles de @dr-ranooo , je clôture pour l'instant :-/

**Comment by dr-ranooo** [comment]
Désolé je n’ai pas vu tes réponses. 
Avec la mise à jour, ça fonctionne. Merci en tout cas, ça rend Weda beaucoup plus fluide.
