### ISSUE TITLE
Dysfonctionnement du tooltip avec appui sur Alt sur Mac

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#303]
L'appui sur Alt 2 fois sur Mac fonctionne bien mais il est aussi déclenché lors de l'appui sur Alt+V sur certaines pages

**Comment by Refhi** [comment]
=> comportement à différencier entre win et ios

**Comment by Refhi** [comment]
Normalement c'est bon.
@Abeldvlpr je peux te laisser vérifier que je n'ai rien cassé sous Mac ?
merci :)
