### ISSUE TITLE
bug sur le lien vers la fiche des raccourcis, erreur 404

### ISSUE THREAD

**Issue by Dr-Vaucel** [Refhi/Weda-Helper#305]
**Décrivez le bug**
Merci de décrire succinctement le bug ex. "les tabulations en consultation ne fonctionnent pas".

**Comment le reproduire**
bug sur le lien vers la fiche des raccourcis, erreur 404

**au besoin une capture d'écran (Maj+Win+S)**
![image](https://github.com/user-attachments/assets/4feec9ae-fbef-421a-b0e5-e68f0710fcf2)

**votre système**
 - Navigateur web [. chrome,

**Comment by Abeldvlpr** [comment]
Corrigé
