### ISSUE TITLE
Bug companion envoi montant vers le TPE

### ISSUE THREAD

**Issue by joellebatot** [Refhi/Weda-Helper#307]
L'envoi du montant du paiement vers le TPE est un peu aléatoire... ça fonctionne et puis d'une consult à l'autre, ça ne fonctionne plus (et puis après ça peut remarcher, incompréhensible)

Suis sur Windows avec Chrome

(c'est une de mes features préférées l'envoi du montant auto j'avoue)

**Comment by Refhi** [comment]
le problème peut se situer à différents endroits :
- un bug lors de l'envoi au TPE de la part de WH ou que le Companion ne recoive pas l'info (improbable). Pour tester, je t'invite à aller à l'accueil d'un dossier patient, appuyer sur F12, puis cliquer sur "Console". Ensuite de cliquer sur le "W" de l'extension, puis "TPE bis". Il nous faudrait une capture d'écran de ce qui se passe à ce moment.
![image](https://github.com/user-attachments/assets/cdf15343-416c-4084-83ea-3c7dc58575a7)
- le lien réseau est capricieux => ouvre une console et tape "ping -n 1200 ladresseipdetonTPE" et laisse tourner. au bout de 20 minutes, regarde le résultat : si ça n'est pas "perte 0%", il y a un problème de réseau => voir avec ta maintenance informatique
- le TPE est capricieux ! => tu peux tester en utilisant le bouton "TPE bis" en cliquant sur le bouton W du premier point, et d'envoyer des dizaines d'instructions.

=> je ferme le ticket pour l'instant : en fonction du niveau où se situe le problème, je t'invite à ouvrir un nouveau ticket ici, sur le github du Companion, ou à voir avec ton fournisseur TPE/ta maintenance réseau

Bon courage :)
