### ISSUE TITLE
Weda Compagnon - proposer redémarrage auto

### ISSUE THREAD

**Issue by Dr-Vaucel** [Refhi/Weda-Helper#311]
**Décrivez le bug**
Bonjour Hervé,
Quand je modifie les options du compagnon on me demande toujours de redémarrer le compagnon.
Ne serait-il pas possible que lors de modification il redémarre tout seul ? 
Si cela n'est pas possible est ce qu'il est possible de rajouter une option dans le menu déroulant : redémarrer le compagnon ? 
![image](https://github.com/user-attachments/assets/213ac84c-96f9-4c24-a230-125d7af1f3f4)

**votre système**
 - OS: windows 11
 - Navigateur web chrome

**Comment by Abeldvlpr** [comment]
Bonjour,

L'implémentation actuelle du Companion rend un redémarrage de l'application trop complexe à mettre en place (nécessiterait un second programme).
Notez cependant que seule la modification du port du companion (ce qui est exceptionnel) nécessite un redémarrage du companion. Toutes les autres options sont prises en compte sans nécessité de redémarrer l'applciation.

Nous n'allons donc pas implémenter cette fonctionnalité pour l'instant.
