### ISSUE TITLE
disparition de la miniature ALT+V et ALT+A dans l'onglet FSE (voulu ? j'ai vu un fix dans le fil)

### ISSUE THREAD

**Issue by Dr-Vaucel** [Refhi/Weda-Helper#314]
**Décrivez le bug**
Bonjour il semblerait que les petite miniature de ALT+V et ALT+A est disparu de la partie FSE

**Comment le reproduire**
Lors de la réalisation d'une FSE; les miniatures n'apparaisse plus sur valider ou annuler et cela dans tous les modes : normal, dégradé, téléconsultation, (et avec sous sans carte vitale)

**au besoin une capture d'écran (Maj+Win+S)**
Miniature manquante
![image](https://github.com/user-attachments/assets/b53be8b3-1fd6-46e8-b3bf-00801c84335c)

Les miniatures dont je parle : 
![image](https://github.com/user-attachments/assets/e137faed-8628-4eea-93a9-9a2e0141d622)

**votre système**
 - OS: windows 11
 - Navigateur web chrome

Merci

**Comment by Refhi** [comment]
Merci pour le ticket :)

Un fix est fait dans https://github.com/Refhi/Weda-Helper/commit/e54d68a173b782b300eb35a8afa44b384befb234

Prévu pour la 2.9 donc
