### ISSUE TITLE
option copier NIR/secu se désactive au DOM refresh

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#32]

**Comment by Ttt131** [comment]
même problème qu'avec les outils de Weda ? (IMTi et INS)

**Comment by Refhi** [comment]
fix dans le 1.4.4 (publication à venir dans les jours qui suivent)

**Comment by Refhi** [comment]
> même problème qu'avec les outils de Weda ? (IMTi et INS)

est-ce que tu peux préciser ?

**Comment by Ttt131** [comment]
> > même problème qu'avec les outils de Weda ? (IMTi et INS)
> 
> est-ce que tu peux préciser ?

Le bandeau INS et le résultat de la requête IMTi disparaissent de la page. Il faut la recharger complètement pour faire réapparaître le bandeau INS, la requête IMTi est perdue.

**Comment by Refhi** [comment]
ah, en effet, bien vu. Le problème est effectivement lié, mais sur la recherche INS/IMti, je n'ai pas la main pour réparer.

Sinon corrigé dans la 1.5
