### ISSUE TITLE
lecture CV lors de création FSE

### ISSUE THREAD

**Issue by rrrrr09** [Refhi/Weda-Helper#33]
Bonjour
sous windows 11 family / chrome

lors de la création d'une FSE la carte vitale n'est pas lue il faut recliquer manuellement sur la fenêtre qui s'ouvre
cf capture d'écran avec ma CV (désolé pour la console mais je ne sais pas si ce sont les infos qu'il te faut)

Si je lis la CV avant cela fonctionne

Autre "bug" la cotation par défaut (G) ne fonctionne pas chez moi

encore merci 

![Capture d'écran 2024-01-19 205738](https://github.com/Refhi/Weda-Helper/assets/157175358/3b7da151-402b-4996-a6a4-b66971b3b58b)

**Comment by Refhi** [comment]
Parfait bug report merci, j'ai pas mal d'info.
Besoin de 2-3 supplémentaires : 
- si tu ferme avec le bouton bleue la mini-fenêtre "carte vitale non lue" puis que tu fais alt+c pour lire la carte vitale est-ce que ça fonctionne ?
- mon hypothèse première est que ce problème apparaît sur une lecture trop précoce de la cv. est-ce que ton pc est plutôt rapide ? Ou rame parfois ?
- j'ai fait des modifs sur la façon dont la CV est lue automatiquement dans la version 1.4.4 que je vais déployer dans les jours à venir. Pourras-tu me dire à ce moment si ça fonctionne mieux stp ?

Aussi, pour la cotation par défaut, je présume que tu l'a bien enregistré dans les options de l'extension ?
Après la cotation par défaut ne s'affiche QUE si tu utilises les touches "n" et "o" pour valider les questions "accident droit commun" et "ald", est-ce que tu peux me confirmer que ça bloque également, et si oui, me renvoyer un screenshot comme tu viens de faire ?

Merci :)

**Comment by rrrrr09** [comment]
L'ordi est plutôt rapide par contre nous sommes en réseau pour les FSE et malgré une connexion en Ethernet c'est parfois l'accès au serveur qui rame un peu (c'est l'ordi du secrétariat qui nous sert de serveur). c'est du coup peut être ca le problème ...

je regarde pour la lecture CV en fermant la mini fenêtre lundi et je te fais un retour

Pour la cotation oui bien sur enregistrée dans les options, par contre effectivement je n'utilise pas les touches n et o pour valider.
Pareil je te dis ca lundi (FSE en réseau oblige)

merci

**Comment by rrrrr09** [comment]
Salut,
voici mon retour :

1/ _si tu ferme avec le bouton bleue la mini-fenêtre "carte vitale non lue" puis que tu fais alt+c pour lire la carte vitale est-ce que ça fonctionne ?_
oui ca lit la carte vitale pas besoin de refaire refaire alt+C

2/ Pour la cotation par défaut ca fonctionne avec n et o

merci

**Comment by Refhi** [comment]
Merci pour les retours.

Je viens de publier la 1.5, j'espère qu'elle sera déployée pour le 29. Peux-tu me dire (en vérifiant la version de l'extension : c'est celle avec les boutons au-dessus du menu déroulant de choix de médicaments) si ça marche mieux ?

**Comment by Refhi** [comment]
Ça risque d'être complexe 🤔

Je vais essayer de comprendre quels est la meilleure façon de déclencher la lecture de la CV au bon moment.

Note : probablement quelque chose avec le window load
`window.addEventListener('load', function() {` ?

**Comment by Refhi** [comment]
peux-tu me dire si ça fonctionne suite à la 1.7 stp ?
Sinon j'ai encore ajouté un autre détail sur la 1.8 qui ne devrait pas tarder

**Comment by rrrrr09** [comment]
je te dis ca lundi a ma reprise
merci pour le retour au dossier après impression sur la 1.6 
presque hâte de reprendre pour voir les améliorations de la 1.7

**Comment by Refhi** [comment]
re, as-tu de l'amélioration sur ce point ? :-/
Sinon la v1.8 ne devrait pas tarder

**Comment by rrrrr09** [comment]
Salut
désolé pour le retard mais j'attendais d'essayer de comprendre
ca marche a peu près une fois 1 sur 3 sans que je sache pourquoi
Apres pour le moment je suis sous wedaconnect 2.6 donc je ne sais pas si cela a un impact sur cette fonction ( j'ai bien compris qu'il faudrait attendre d'être en v3 pour avoir la lecture automatique de CV)

**Comment by Refhi** [comment]
merci pour le retour
dans la 1.8 je modifie encore 2-3 choses, et effectivement avec wedaconnect3.0 ça contournera le problème puisque la CV sera lue automatiquement dès l’insertion (sauf dans les pages cs ou prescription)

**Comment by rrrrr09** [comment]
Salut,
j'ai pu tester la 1.8.1 hier matin, pas de modification / 1.7, ca a marché de façon aléatoire.
Ne t'embête pas avec ce problème si weda connect 3 règle le problème on va attendre. et je pense que ca vient aussi de notre config en réseau.
Je continue de tester ca dans la semaine et je te fais un retour
