### ISSUE TITLE
Feature request : selection automatique du patient à la lecture de la CV

### ISSUE THREAD

**Issue by Ttt131** [Refhi/Weda-Helper#34]
Bonjour, pourquoi pas une lecture automatique à l'insertion de la carte vitale ?
ça permettrait une ouverture automatique du dossier patient si un seul profil sur la carte, si plusieurs profils la fenêtre habituelle proposer les différents profils.

**Comment by Refhi** [comment]
Bonjour,
merci pour la suggestion.
En pratique déclencher une lecture de la carte vitale au moment de l'insersion de la carte impliquerais beaucoup de conséquences en terme de développement : je devrais me plonger dans la doc du protocole pcsc ou du galss.ini (arg.) donc à mon niveau pas possible, désolé.
Par contre l'idée de lire automatiquement le profil du patient s'il est le seul sur la carte vitale, ça c'est faisable et ça rajouterais du confort.

**Comment by Refhi** [comment]
Bonne idée, je regarde ça dès que j'ai weda connect 3 à ce moment :)

**Comment by Refhi** [comment]
ouverture automatique d'un patient seul sur la carte => fait dans 1.6
reste la lecture auto de la carte avec Weda Connect, probablement pas avant quelques semaines

**Comment by DrFloW71** [comment]
Voici ce que ça donne quand on insère une CV avec le Weda connecteur V3:
![image](https://github.com/Refhi/Weda-Helper/assets/157386513/aaf4ca8c-174a-4c87-ad6c-42e5669bc74b)
Donc peut être détectable facilement!
Si vous ne l'avez pas vous pouvez demander à votre tech et il vous l'installera. Sinon vous pouvez essayer > weda.actions.showWedaInstall() dans la console.

**Comment by Refhi** [comment]
fait ! C'est vrai que c'est tout confort. A venir avec la 1.7.

**Comment by Ttt131** [comment]
Merci ! J'ai hâte !
