### ISSUE TITLE
proposition de raccourcis clavier 

### ISSUE THREAD

**Issue by matktam** [Refhi/Weda-Helper#35]
Proposition de raccourcis  : 

- Alt + R pour accéder la fenêtre de recherche  de patient  "...secure.weda.fr/FolderMedical/FindPatientForm.aspx"

**Comment by Refhi** [comment]
pour préciser : ce sera effectif dans la version v1.6. Il faudra retourner dans le panneau des raccourcis pour y mettre le raccourcis de ton choix.
