### ISSUE TITLE
Amélioration: Ajout du montant pour la cotation par défaut

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#38]
Pour compléter la fonction "Cotation par défaut dans la FDS" il serait sympa de pouvoir ajouter un montant différent par défaut pour les médecins S2 ou pratiquant les DE.
Merci!

**Comment by Refhi** [comment]
La solution la plus robuste serait pour moi de "taper" sur le bouton d'une cotation présente dans les favoris.

On pourrait imaginer que l'extension validerai une cotation favorite nommée "défaut" ou "fav" par exemple

Ça rendrai aussi dans l'ensemble le système d'autocompletion de la fse plus fiable

=> prévu pour la 1.6

**Comment by Refhi** [comment]
corrigé dans la 1.6
