### ISSUE TITLE
BUG: fermeture automatique de la fenêtre PDF

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#39]
Fermeture automatique de la fenêtre de prévisualisation du PDF après demande d'impression, si le lien avec le companion est actif ne fonctionne pas ni sur EDGE ni sur CHROME. Y a t'il une MàJ du companion à faire?

**Comment by Refhi** [comment]
Bonjour,
Pas besoin de mettre à jour le Companion, je regarde quel est le problème. Tu as bien la version 1.5 de l'extension ? (dans about:extensions active le mode développeur en haut à droite pour que le numéro de version s'affiche)

**Comment by DrFloW71** [comment]
Salut, oui je suis bien en 1.5 avec les nouvelles fonctionnalités. Niveau impression c'est IDEM que sur le 1.4

**Comment by matktam** [comment]
Fonctionne bien chez moi, sous chrome, Edge ou brave

**Comment by DrFloW71** [comment]
> bizarre, de mon côté sur chrome et chromium c'est fonctionnel. J'ai mis en place des éléments pour faciliter le débugage dans le code, mais ce ne sera pas chez toi avant quelques jours (semaine?) le temps que je déploie la version suivantes. En attendant, peux-tu me confirmer :
> 
> * que l'impression "zero-click" fonctionne bien ? (donc qu'en faisant ctrl+P ou équivalent l'impression est lancée sans autre action grâce au Companion ?)
> * peux-tu faire (sous chrome) ctrl+maj+C puis cliquer sur le bouton "Fermer mais rester sur la page appelante" après avoir lancé une impression. De là il doit t'ouvrir la console. Peux-tu m'en envoyer une copie d'écran stp ? (ou simplement me confirmer que l'élément alors sélectionné est bien :
>   `<input type="button" name="ctl00$ContentPlaceHolder1$ViewPdfDocumentUCForm1$ButtonCloseStay" value="Fermer mais rester sur la page appelante" onclick="javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder1$ViewPdfDocumentUCForm1$ButtonCloseStay&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))" id="ContentPlaceHolder1_ViewPdfDocumentUCForm1_ButtonCloseStay" class="buttonclose" style="width:49%;">`
> * enfin peux-tu cliquer sur "console" après la manip précédente et me joindre également une capture d'écran ?
> 
> Merci d'avance si tu es ok j'aurais probablement besoin d'autres échanges d'info pour pouvoir corriger la problématique

Je n'ai qu'un bouton fermer. Je n'ai pas de bouton fermer et rester sur la fenêtre appelante. Le soucient vient surement de là. Peut être ue cela vient de comment Weda ouvre les pdf?

![image](https://github.com/Refhi/Weda-Helper/assets/157386513/70d6d2a6-a793-4ea5-ad7f-2a0dfcadf541)
