### ISSUE TITLE
Impression PDF puis envoi dans le DMP

### ISSUE THREAD

**Issue by tpuszkarek** [Refhi/Weda-Helper#40]
Bonjour,

Merci pour cet immense travail qui me facilite grandement la vie au quotidien.

Un petit détail : la v1.5 amène la "fermeture automatique de la fenêtre de prévisualisation du PDF après demande d'impression, si le lien avec le companion est actif" qui est une excellente idée et fonctionne parfaitement chez moi.
Par contre, l'étape d'envoi automatique dans le DMP est visiblement court-circuitée.
Serait-il possible de combiner les deux, c'est à dire fermer automatiquement la fenêtre tout en permettant l'envoi automatique dans le DMP ?

Merci !

**Comment by Refhi** [comment]
en effet !
Je peux voir pour intégrer cette étape après l'impression, en cliquant sur le bouton "envoi au DMP" si la case est cochée, ça permettra de ménager les deux

**Comment by Refhi** [comment]
En attendant l'option est désactivable dans les options

**Comment by Refhi** [comment]
De mon côté la fonctionnalité est cassée, même quand je désactive l'extension.
Peux-tu également essayer après avoir désactivé temporairement l'extension stp et me donner ton retour ?
