### ISSUE TITLE
Afficher systématiquement l'historique du patient pendant une consultation/ordo/etc. mais dans une colonne à gauche de l'écran.

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#41]

**Comment by Refhi** [comment]
ça commence à prendre forme, mais c'est complexe...

![image](https://github.com/Refhi/Weda-Helper/assets/2778215/2d940b1a-dbc7-4cb5-a0a1-30ed3365a52c)

**Comment by Refhi** [comment]
ça avance, mais c'est complexe

![image](https://github.com/Refhi/Weda-Helper/assets/2778215/844eb232-d613-465d-9263-90dc126a3e93)

**Comment by DrFloW71** [comment]
Wahou! Bravo c'est déjà top! C'est possible de faire plus large pour la visualisation de plus de consultations sans scroller?

**Comment by Refhi** [comment]
C'est à dire de passer de 25% en largeur à 30-35%?

Au passage sur quelles pages ça te paraît pertinent que cette colonne à gauche soit visible ? Seulement les cs ou aussi les prescriptions ?

**Comment by DrFloW71** [comment]
Salut, oui 1/3 de la page c'est pas mal je pense. 
Maintenant que tu le dis la plupart des pages comprennent 2 blocs donc un présentation similaire sur certif, prescription, courriers serait pas mal!
J'ai un ultrawide à la maison, je pense que ça va me donner envie d'en prendre un cabinet...

**Comment by Refhi** [comment]
Ouf !

Pour le moment juste sur la page des consultations. Peut-être à terme sur les autres pages...

Il m'a donné du fil à retordre celui-là...

![Capture d’écran du 2024-02-14 23-17-16](https://github.com/Refhi/Weda-Helper/assets/2778215/dbdb64c2-b017-4017-aed0-4e26e37ebaec)

**Comment by Refhi** [comment]
fait dans la 1.7
