### ISSUE TITLE
Modification: fenêtre confidentialité enfants

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#42]
A mon avis compliqué à développer via l'extension mais si un dev Weda passe dans le coin on ne sait jamais: La fenêtre de confidentialité qui s'affiche systématiquement pour les enfant alors que rie de confidentiel dans 99% des cas... Il suffirait de la remplacer par un bouton à cocher en cas de besoin!

**Comment by Ttt131** [comment]
Je pense que tu rêves, ils ne s'intéressent déjà pas aux tickets ni aux remontées qu'on fait sur la communauté...
Mais je suis d'accord il y a des améliorations à faire.
Globalement : stop aux popups et aux clics inutiles !

**Comment by DrFloW71** [comment]
> Je pense que tu rêves, ils ne s'intéressent déjà pas aux tickets ni aux remontées qu'on fait sur la communauté... Mais je suis d'accord il y a des améliorations à faire. Globalement : stop aux popups et aux clics inutiles !

Je suis un doux naïf!

**Comment by Refhi** [comment]
C'est le problème des contraintes légales...
J'ai peur qu'en développant un contournement on ne se mette potentiellement en difficulté légale.
J'imagine que je peux par contre automatiquement désactiver le message et décocher l'envoi au dmp si le message a été détecté et fermé automatiquement.
Libre au praticien de réactiver l'envoi après coup ? 🤔

J'attends vos retour avant de plancher sur le sujet.

(j'ai les mêmes arrières-pensées pour l'ordo numérique :-S )

**Comment by Ttt131** [comment]
> C'est le problème des contraintes légales...
> J'ai peur qu'en développant un contournement on ne se mette potentiellement en difficulté légale.
> J'imagine que je peux par contre automatiquement désactiver le message et décocher l'envoi au dmp si le message a été détecté et fermé automatiquement.
> Libre au praticien de réactiver l'envoi après coup ? 🤔
> 
> J'attends vos retour avant de plancher sur le sujet.
> 
> (j'ai les mêmes arrières-pensées pour l'ordo numérique :-S )

Pour le secret il me semble qu'il est possible de le désactiver en mettant 18 ans comme âge limite dans les paramètres.

**Comment by Refhi** [comment]
En attendant je vais voir pour mettre les boutons oui/non accessibles à alt+v et alt+a avec une info-bulle l'encourageant. Ça limitera la gêne au quotidien ? 🤔

**Comment by Refhi** [comment]
Qu'est ce que tu entends par sélection du numéro de facturation ? 🤔
J'ai la sensation que c'est hors-sujet du ticket présent, si tu le souhaites ouvres un autre ticket séparé en détaillant bien, si c'est simple je peux regarder

Sinon oui pour les pop-up c'est pénible mais j'ai l'impression que c'est la même chose que pour les questions oui/non de la fse : une obligation légale théoriquement pertinente qui perd tout son sens au quotidien...

**Comment by Refhi** [comment]
fait dans la 1.6
