### ISSUE TITLE
Raccourci Esc pour tous les boutons annuler de Weda

### ISSUE THREAD

**Issue by Ttt131** [Refhi/Weda-Helper#43]
Pour pouvoir fermer les différents popup de l'enfer simplement par la touche Esc.
Qu'en pensez-vous ?

**Comment by Refhi** [comment]
Mmmm je t'avoue que ça sera plus compliqué à faire que de simplement recycler le "alt+a" qui sert déjà à cliquer sur les boutons annuler

**Comment by Ttt131** [comment]
> Mmmm je t'avoue que ça sera plus compliqué à faire que de simplement recycler le "alt+a" qui sert déjà à cliquer sur les boutons annuler

En effet !
