### ISSUE TITLE
Proposition: Affichage auto ordo types +/- ttt de fond

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#45]
Petite idée du jour: afficher les ordo types directement lorsque l'on arrive sur la page de prescription. Ca permet de gagner un clic en cas d'utilisation d'une ordo type et ne fait pas de clic en plus en cas de prescription libre ou RO.
Autre idée mais peut être plus dur à faire: afficher d'emblée les ordotypes et les ttt de fond côte à côte (1/3 de page pour chaque).

Voici déjà mon code pour afficher d'emblée les ordos types avec Tampermonkey:

// ==UserScript==
// @name         Clic auto sur prescriptions types
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Automatisation de clic sur le bouton de prescription sur weda.fr
// @author       Vous
// @match        https://secure.weda.fr/FolderMedical/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    window.addEventListener('load', function() {
        var button = document.getElementById('ContentPlaceHolder1_ButtonPrescritionType');
        if (button) {
            button.click();
        }
    });
})();

**Comment by Refhi** [comment]
Mmmm

Pour l'auto-click, c'est assez simple. J’implémenterais ton code à l'occasion.

Pour le cote-cote, pas possible de mon côté j'en ai peur

**Comment by DrFloW71** [comment]
Oui j'ai réfléchi mais ça parait compliqué vu qu'ouvrir une fenêtre ferme l'autre....

**Comment by Refhi** [comment]
ajouté dans la 1.8
