### ISSUE TITLE
retour dossier après impression

### ISSUE THREAD

**Issue by rrrrr09** [Refhi/Weda-Helper#46]
Bonjour
est il possible que la fonction impression via le companion avec Crt+P déclenche aussi un retour au dossier (appui sur W) ?
ca ferait gagner un clic :)

merci

**Comment by Refhi** [comment]
Techniquement c'est jouable

Du coup je vais mettre en option quelque chose du genre : 
"après impression via le Companion :  
- ne rien faire
- fermer la previsualisation
- retourner au dossier patient"

**Comment by rrrrr09** [comment]
Ça serait parfait

**Comment by matktam** [comment]
Le choix de le mettre en option est une bonne idée 👍

**Comment by Refhi** [comment]
fait dans le 1.6
