### ISSUE TITLE
Proposition : ajout d'un raccourci pour les antécédents et l'historique

### ISSUE THREAD

**Issue by tpuszkarek** [Refhi/Weda-Helper#48]
Bonjour,
Jusqu'à présent, j'utilisais plusieurs onglets afin de noter mon compte-rendu de consultation tout en rédigeant une ordonnance, un courrier, etc.
Je me suis remis à n'en utiliser qu'un seul grace à cette extension et aux raccourcis permettant de gagner beaucoup de temps.
Un petit détail me ferait encore plus gagner en confort : dans la page "consultation", est-il possible de créer un raccourci permettant d'afficher/masques les antécédents et l'historique du patient (qui s'affichent lorsqu'on clique sur les liens ATDS et HISTORIQUE en haut à droite) ?
Merci pour tout ce travail !

**Comment by Refhi** [comment]
Bonjour, merci pour les encouragements :)

#41 aborde la même thématique, penses-tu que ça répondrait à ta problématique ?

**Comment by tpuszkarek** [comment]
Oui je pense, merci ! Désolé, j'avais lu ce post mais n'avais pas fait le rapprochement.

**Comment by Refhi** [comment]
closed as dup of #41
