### ISSUE TITLE
Proposition: Barre de navigation

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#49]
Vieille idée que j'avais soumise à un commercial Weda il y a quelque temps sans qu'il ne s'en émeuve tellement il était fier de son menu W aujourd'hui tellement désuet: Regrouper tous les onglets du W dans une seconde barre de navigation à gauche ( ou en haut de l'écran) pour s'éviter ce laborieux passage sur le W. 
Bon grâce aux raccourcis clavier de Weda helper c'est moins nécessaire mais je laisse l'idée là au cas ou.

**Comment by Refhi** [comment]
Techniquement faisable, et intéressant, mais effectivement avec les raccourcis claviers ça rend l'intérêt moins évident 🤔

Si quelqu'un veux mettre ça dans un pull request pourquoi pas, mais pour l'instant pas prévu (roadmap trop chargée), désolé
