### ISSUE TITLE
Consultation défaut ne fonctionne pas

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#51]
Je peux te fournir quoi pour t'aider à débug?
![image](https://github.com/Refhi/Weda-Helper/assets/157386513/237df0d6-5213-4845-ae92-ff01f84e5e08)

**Comment by Refhi** [comment]
Est-ce que tu as activé l'option dans les options ? 🤔 Je crois qu'il faut que je fasse gaffe aux options par défaut après mise à jour... J'ai un collègue qui a été en difficulté à cause de ça...
Aussi Peux-tu me confirmer que tu utilises bien "n" et "o" pour valider les deux questions oui/non ?

**Comment by DrFloW71** [comment]
Salut, oui option bien activée. C'est clair dans les options pas de souci.
Par contre je n'utilise pas n/o vu que j'ai les cases précochées via script. Ca doit venir de là.

**Comment by Refhi** [comment]
En effet, car la cotation par défaut se déclenche lors de la pression sur la touche n ou o qui valide la seconde question.

Je verrai si je peux inscrire la cotation par défaut en amont à l'occasion, ça devrait régler le problème

**Comment by DrFloW71** [comment]
C'est tout bon en cliquant sur "n" effectivement! Top!

**Comment by Refhi** [comment]
@DrFloW71 j'ai tendance à ne pas forcément voir que les textes d'options peuvent être durs à comprendre. est-ce que je pourrais te demander un coup de main pour me pointer ceux qui manquent de clarté et éventuellement proposer une reformulation ?
Merci d'avance :)
