### ISSUE TITLE
raccourcis pour les courbes pediatriques

### ISSUE THREAD

**Issue by Jitto31** [Refhi/Weda-Helper#52]
bonjour

il y a énormément de clics pour obtenir les courbes pédiatriques, y a t il moyen de créer un bouton a coté des mesures pour ouvrir les courbes plus rapidement?

Actuellement il faut
> remplir la case avec la mesure> cliquer sur "enregistrer"> clic sur historique> clic sur "visualiser les valeurs>courbe panneaux déroulants courbes pédiatriques > choisir la courbe qu'on veut

Souhait: 
On remplis la case avec la valeur> on appuis sur un bouton a coté de la valeur qui ouvre directement la courbe, au pire on se retrouve dans "visualiser les valeur" et on clic sur un bouton de la courbe qu'on veut avec des boutons au lieu du volet déroulant

Si c'est faisable ca serait génial!

Merci pour ton travail dans tout les cas, l'extension me change la vie!

**Comment by Refhi** [comment]
Bonsoir,

Bonne idée !

Je planifie ça à l'occasion

Et merci pour le retour encourageant, ça me motive à poursuivre 😁

**Comment by Refhi** [comment]
Fait !

Ça a été franchement fun et satisfaisant à coder celui-là


![0-1708206242829](https://github.com/Refhi/Weda-Helper/assets/2778215/1e01f659-09e0-4ca3-911a-53ae4368323b)
