### ISSUE TITLE
Proposition : colorer une liste de mots clés

### ISSUE THREAD

**Issue by Ttt131** [Refhi/Weda-Helper#53]
dans la liste des documents type il est parfois difficile de retrouver un item facilement
pourquoi pas une liste de quelques mots clés personnalisables qui seraient affichés en couleur lorsqu'ils sont détectés ?
Par exemple : mot clé "sport" = vert
le titre du document type "certificat de sport" est affiché en vert

**Comment by DrFloW71** [comment]
Bonne idée ergonomique! Je pense que surligner un mot dans une page s'il est détecté ne devrait pas être trop compliqué.

**Comment by DrFloW71** [comment]
Petit exemple pour surligner le mot voie: 
![image](https://github.com/Refhi/Weda-Helper/assets/157386513/aeb85f7b-9496-4477-abb4-eab21dc4eec7)

**Comment by DrFloW71** [comment]
Voici le script si ça peut aider:

// ==UserScript==
// @name         Surligner un mot spécifique sur une page
// @namespace    http://tampermonkey.net/
// @version      0.14
// @description  Surligner un mot spécifique en jaune fluo sur une page si détecté lors de son chargement.
// @author       Votre Nom
// @match        https://secure.weda.fr/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // Mot à surligner
    var motASurligner = "voie";

    // Surligner le mot spécifique
    function surlignerMot() {
        var bodyText = document.body.innerHTML;
        var regExp = new RegExp(motASurligner, "gi");
        var nouveauContenu = bodyText.replace(regExp, '<span style="background-color: yellow;">$&</span>');
        document.body.innerHTML = nouveauContenu;
    }

    // Surligner le mot spécifique lorsque la page est chargée
    surlignerMot();
})();

**Comment by Ttt131** [comment]
Petite difficulté : à afficher uniquement sur les pages "demande" et "certificat" sinon ça risque de polluer

**Comment by Refhi** [comment]
Mmmm....

Assez fastidieux à développer j'avoue, vu les différents cas de figure à prendre en compte.

Si quelqu'un veut se pencher sur le code (donc avec l'intégration dans les options.hs, le content.js etc.) je veux bien l'intégrer mais je ne me pencherais pas dessus directement, désolé :-/

En attendant je propose différentes voies pour limiter le problème :
- utiliser les sous-dossiers pour classer les documents/conseils etc.
- les créer avec des lettres capitales sur le mot-clé le plus important
- utiliser ctrl+F dans le navigateur
