### ISSUE TITLE
Améliorer la description des options

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#56]
Aujourd'hui impossible d'imprimer, je n'ai plus de template d'impression dispo! Hier tout allait bien! Le template réapparait lorsque je désactive Weda Helper.
![image](https://github.com/Refhi/Weda-Helper/assets/157386513/2a6718ab-630a-47c7-adce-73f8703e61a1)
Une idée? Je suis en PLS sans Weda Helper ^^

**Comment by DrFloW71** [comment]
EDIT: Fonctionne sous EDGE! Bizarre...

**Comment by DrFloW71** [comment]
EDIT2:

Trouvé: mon tech WEDA m'avait activé l'ordo numérique et j'avais activé la coche auto donc logique qu'il ne me propose plus les Template d'impression...

PAS de BUG du coup!

![image](https://github.com/Refhi/Weda-Helper/assets/157386513/01393631-3b5c-4f2c-90d5-b0de68ee337d)
Juste peut être pour être plus clair dans les options mettre "Coche automatiquement la case ordonnance numérique" dans les ordos ou dans les autres docs.

**Comment by Refhi** [comment]
@DrFloW71  j'ai tendance à ne pas forcément voir que les textes d'options peuvent être durs à comprendre. est-ce que je pourrais te demander un coup de main pour me pointer ceux qui manquent de clarté et éventuellement proposer une reformulation ?
Merci d'avance :)

**Comment by Refhi** [comment]
Merci ! Intégré à la v1.8
