### ISSUE TITLE
bug FSE lecture automatique CV

### ISSUE THREAD

**Issue by Jitto31** [Refhi/Weda-Helper#61]
Bonjour
quand on ouvre le dossier via lecture automatique de la CV (génial par ailleurs😍)
lorsqu'on créer la FSE, les cases ne se coches pas quand on clique sur "N", il faut cliquer sur la FSE et là on peut utiliser le N pour remplissage auto de la FSE!

Merci

**Comment by Jitto31** [comment]
j'ai eu le bug 2 fois ce matin, mais pas de soucis en fin de matinée, peut etre une fausse alerte!

**Comment by Refhi** [comment]
Merci pour le retour
Pour l'instant je clôture le ticket, mais n'hésite pas à y répondre si tu vois de nouveau le problème, je verrai l'alerte et rouvrirai le ticket
