### ISSUE TITLE
Rafraichissement des messages MSSANTE

### ISSUE THREAD

**Issue by Ttt131** [Refhi/Weda-Helper#64]
Lors de la consultation des messages dans "vos échanges sécurisés" la liste des messages ne se rafraichit pas après synchronisation, il faut quitter la page et y revenir pour que les nouveaux messages s'affichent.

**Comment by Jitto31** [comment]
si par hasard un rafraichissement automatique de temps en temps sans aller dans "vos échanges sécurisée" ca serait encore mieux, mais je ne sais pas si c'est réalisable ^^

**Comment by Refhi** [comment]
ça malheureusement probablement pas :'-(

**Comment by tpuszkarek** [comment]
Bonjour. Pour cela, j'utilise l'extension "Tab Reloader" qui fonctionne bien.

**Comment by Refhi** [comment]
> Bonjour. Pour cela, j'utilise l'extension "Tab Reloader" qui fonctionne bien.

Excellente idée.

Je regarde si je peux obtenir quelque chose de simple dans weda-helper qui ferait la même chose sans nécessité d'extension supplémentaire.

**Comment by Refhi** [comment]
Implémenté pour la 1.9
