### ISSUE TITLE
affichage historique dans courrier

### ISSUE THREAD

**Issue by rrrrr09** [Refhi/Weda-Helper#65]
Bonjour

Merci pour le 1.8.1 !

est il possible d'avoir (en option) l'affichage de l'historique dans la colonne de gauche quand on fait un courrier comme pour les consultations ?

et question bonus : est il possible que lors d'une ouverture de consultation le curseur soit automatiquement placé dans la partie "histoire de la maladie" ? J'en ai marre de taper mes consults dans le vide en oubliant de cliquer dans la case :(

encore merci pour ton taf

**Comment by Refhi** [comment]
:)

pour le focus automatique dans "histoire de la maladie" c'est censé être réglé avec la 1.8.1 normalement :-S est-ce que tu peux me confirmer ?

Sinon pour l'affichage dans les courriers, pourquoi pas à l'occasion :) (Pour l'instant je vais lever le pied sur le développement de l'extension - le temps que ça prend est assez ahurissant - et surtout me concentrer sur les corrections de bug

Je laisse le ticket ouvert, quand j'aurais de nouveau envie de mettre le nez dedans :)

**Comment by rrrrr09** [comment]
Oui bien sûr, désolé
Je regarde pour le focus

**Comment by Jitto31** [comment]
le focus remarche avec la mise a jour moi!! merci !!

**Comment by Refhi** [comment]
Fait dans la 1.9 :)
