### ISSUE TITLE
Proposition: Sélection auto biologie pour les ordos numériques

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#67]
Pour gagner 2 clics: sélectionner automatiquement le type biologies pour les ordos numériques de biologies. (La plupart du temps on prescrit des bio, et il suffit de changer si on prescrit un autre type.)

![image](https://github.com/Refhi/Weda-Helper/assets/157386513/4ce9c74f-3fe8-484a-8a31-6812ed0ae832)

**Comment by Refhi** [comment]
Fait pour la 1.9
