### ISSUE TITLE
Amélioration de la présentation

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#68]
Maintenant que l'extension arrive à une certaine maturité (normalement il n'y a plus pléthore de fonctions complexes à développer), je souhaiterais affiner un peu le Readme, et la présentation de l'extension.
Si vous êtes intéressé, je vous invite à relire le Readme, et à proposer une amélioration de la procédure d'installation.
Je suis également preneur d'une petite Video (1 min ?) pour présenter l'extension et les fonctions principales. Dans l'idée je pourrais la mettre sur la page de présentation de l'extension chrome.
Au passage merci encore à Florian qui a ré-écrit une bonne partie des descriptions d'options :)
Si ça vous tente, je centralise ça sur github :)
Merci d'avance ^^

**Comment by DrFloW71** [comment]
Je regarde ça!

**Comment by Refhi** [comment]
C'est top merci beaucoup !

Penses-tu qu'il faille qu'on détaille un peu plus la procédure d'installation ? 🤔

**Comment by DrFloW71** [comment]
J'ai failli mais en fait tout est déjà très clair dans le .ini

**Comment by Refhi** [comment]
Implémenté dans la 1.9 :) Merci @DrFloW71
