### ISSUE TITLE
Amélioration: ajout facilité d'antécédents depuis la messagerie

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#69]
Pouvoir entrer les antécédents d'un patient depuis la page d'import des courriers. En effet je trouve ça fastidieux sur Weda. On reçoit un courrier qui nous dit par exemple SCA. Il faut ouvrir le dossier du patient puis aller renseigner ce nouvel ATCD...

Peut être serait il possible, une fois le bon patient associé d'afficher le volet ATCD à droite. Ou a minima une icone permettant d'aller ajouter un antécédent directement?

**Comment by Refhi** [comment]
Aie.

Je viens de faire un peu de recherche, et malheureusement, les antécédents ne sont pas facilement accessibles dans une iframe, et leurs urls protégées. En clair si on essaie d'accéder directement aux antécédents (ex. via l'adresse https://secure.weda.fr/FolderMedical/AntecedentForm.aspx par exemple) on se fait déconnecter comme un malpropre. Donc pas possible de mon côté désolé.
