### ISSUE TITLE
Affichage des antécédents en haut de la page de consultation ?

### ISSUE THREAD

**Issue by tpuszkarek** [Refhi/Weda-Helper#70]
Bonjour !
A nouveau, merci pour toutes ces fonctionnalités qui améliorent grandement l'utilisation de Weda.
Depuis la page de consultations, l'affichage de l'historique dans le 1/3 gauche de l'écran m'aide beaucoup. 
Serait-il jouable d'y ajouter l'affichage des antécédents dans le haut de l'écran, exactement comme ce qui se produit actuellement en cliquant sur "ATCD", en gardant le focus de la souris sur l'interrogatoire ?
Merci beaucoup !

**Comment by Refhi** [comment]
Si je comprend bien tu souhaiterai que les atcd soient automatiquement ouverts à l'ouverture des pages de consultation ? 🤔
Normalement c'est assez simple à faire (je n'aurais pas besoin de passer des heures à dompter le CSS)

**Comment by tpuszkarek** [comment]
Oui, c’est exactement ça !
Je suis peut-être le seul que ça aiderait, cela dit.

**Comment by Refhi** [comment]
> Oui, c’est exactement ça ! Je suis peut-être le seul que ça aiderait, cela dit.

😅

Pas forcément, et ça permet de tester de nouveaux usages, et de les mettre en valeur auprès de Weda, pour une future intégration 🤞

C'est aussi l'intérêt de mettre la quasi-totalité des modifs de Weda-helper en option : les utilisateurs peuvent toujours les désactiver si ça les ennuie.

Dans tout les cas je m'occupe de ça à l'occasion 👍

**Comment by tpuszkarek** [comment]
Merci beaucoup !

**Comment by Refhi** [comment]
Fait pour la 1.9
