### ISSUE TITLE
remplissage des unités de normes

### ISSUE THREAD

**Issue by PaulMdu08** [Refhi/Weda-Helper#71]
Salut,
l'objectif idéalement serait de faire figurer dans les cases adhoc,
l'unité utilisée pour chaque mesure,
dans tous les dossiers de Weda
(et non dossier par dossier...)
merci
P.M.

**Comment by Refhi** [comment]
Peux-tu me dire quelles sont les types de données que tu as de base stp ?
Pour l'instant j'ai prévu ça : 'Taille:cm,Poids:kg,Pc:cm,IMC:kg/t²,TAS:mmHg,TAD:mmHg,FC:bpm,Sat:%'

**Comment by Refhi** [comment]
Fait pour la 1.9.

Je laisse le ticket ouvert en attendant tes suggestions pour les unités de base :)

**Comment by PaulMdu08** [comment]
salut et merci pour cette initiative ergonomique
effectivement il serait envisageable de proposer ces normes :  
poids en kg; PAd et PAs en mmHg ou Torr; FC en /mn ou bpm ; IMC en kg/m²; PC en cm; 
bonne journée
P.M.
NB: comment te transmettre mon fichier d'idées "200 idées pour un tera-Weda" ?

**Comment by PaulMdu08** [comment]
test de PJ:
[WEDA 200 idées 2021_11 synthèse.docx.pdf](https://github.com/Refhi/Weda-Helper/files/14565371/WEDA.200.idees.2021_11.synthese.docx.pdf)
[WEDA 200 idées 2021_11 synthèse.docx.pdf](https://github.com/Refhi/Weda-Helper/files/14565372/WEDA.200.idees.2021_11.synthese.docx.pdf)
[WEDA 200 idées 2021_11 synthèse.docx.pdf](https://github.com/Refhi/Weda-Helper/files/14565376/WEDA.200.idees.2021_11.synthese.docx.pdf)

**Comment by Refhi** [comment]
fait dans la 1.9 :)
