### ISSUE TITLE
Suggestion : Choix automatique du type de document dans l'interface courrier

### ISSUE THREAD

**Issue by DocTigs** [Refhi/Weda-Helper#72]
Bonjour,
Une fonctionnalité qui me ferait gagner beaucoup de clics dans la journée, serait que dans l'interface courrier, le type de document par défaut puisse être paramétrable.
Actuellement, le choix par défaut est toujours "Lettre de liaison à la sortie d'un établissement de soin", ce qui parait débile pour un logiciel médical destiné au monde libéral... A chaque courrier il faut que j'aille chercher dans le menu déroulant "CR ou fiche de consultation ou de visite", ce qui est quand même le choix le plus fréquent pour un médecin libéral.
Malheureusement mon "expert weda" ne s'est absolument pas senti concerné.
Merci de tout le travail réalisé !

**Comment by Refhi** [comment]
Bien vu !

Je n'avais pas fait attention à ce problème jusqu'ici.

Deux possibilités : 
- soit je m'arrange pour que Weda-Helper enregistre le dernier choix
- soit je met une option pour qu'on choisisse le choix pertinent dans les options
Une préférence ?

**Comment by Ttt131** [comment]
A mon avis enregistrer le dernier choix est une bonne option, car ça remplit les deux fonctions : à la fois mémoriser le type préféré et être facilement modifiable (pas besoin d'aller dans les options).

**Comment by matktam** [comment]
D' accord avec Ttt131.

**Comment by DrFloW71** [comment]
Salut! Je ne change jamais le type de document mais en effet laisser le dernier choisi serait une bonne solution.

**Comment by DocTigs** [comment]
Bonjour,
Je vote plutôt pour un paramétrage dans les options. La raison : je fais 90% de courrier consultation et 10% d'actes diagnostiques (autres), en alternant sur certaines vacations 1 consult/1acte/1consult.... quand j'ai la machine.
Avec le dernier choix retenu, ça me force à change à chaque fois le type de document quand je suis dans une vacation mixte.
Alors que si c'est un choix par défaut, je laisse en mode "consultation", et je ne modifie que lors des actes diagnostics.
Après c'est une façon de travailler assez spécifique, laisser sur le dernier choix retenu sera déjà un progrès considérable pour moi !
Merci

**Comment by Refhi** [comment]
Dans l'idéal il faudrait même un système de favoris je suppose, peut-être à l'occasion
Pour l'instant j'ai simplement mis le système pour conserver la dernière sélection
A venir dans la v1.10 !
