### ISSUE TITLE
Bug: Problème affichage splitté suite import de document.

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#73]
Pas très embêtant mais je remonte quand même par principe. Suite à un import de document dans une consult les champs de texte reprennent leur taille initiale et il y a superposition avec le champ d'historique.
![image](https://github.com/Refhi/Weda-Helper/assets/157386513/0063ab61-c3b2-4a12-9005-93a8df81a61a)

**Comment by Refhi** [comment]
Je suis en difficulté pour reproduire le bug :-/ que ce soit dans la 1.7.8 ou la 1.8.3

Je retesterais au cabinet médical. En attendant peux-tu me mettre une capture d'écran de la console stp au moment du bug ? (F12 quand le focus est hors d'un champ de texte)

**Comment by DrFloW71** [comment]
Depuis peu le bug a disparu... J'essaie de reproduire!

**Comment by Refhi** [comment]
Je cloture pour l'instant, n'hésite pas à remettre un commentaire si tu vois que le bug se reproduit à nouveau :)
