### ISSUE TITLE
Bug d'affichage : les cadres Weda sont limitées à la moitié de l'espace disponible

### ISSUE THREAD

**Issue by Ttt131** [Refhi/Weda-Helper#74]
Hello
je ne sais pas si tu peux faire quelque chose là dessus, mais il y a un bug de Weda qui me gêne actuellement et qui revient parfois sans que je trouve la cause.
Les différents cadres de Weda sont limités à la moitié de l'espace disponible ce qui est très désagréable, peut on faire quelque chose pour que cela occupe 100% de l'espace ? (j'ai tenté de vider le cache, les cookies, l'option Weda grand écran)

exemples ci dessous 

![image](https://github.com/Refhi/Weda-Helper/assets/77486557/026c504d-305c-4439-94be-83b95cc64cd8)

![image](https://github.com/Refhi/Weda-Helper/assets/77486557/cccc6b53-4690-4878-93c8-e455a6a6337f)

**Comment by Refhi** [comment]
Un bug intermittent, donc ? Aïe. C'est les pires.
as-tu la certitude que ça ne vienne pas de Weda-Helper ? (c'est pas impossible).
Si tu as l'impression que ça puisse venir de Weda-Helper je veux bien de nouvelles captures d'écran avec la console de visible stp
Sinon malheureusement, sans que je ne puisse reproduire le bug de mon côté (jamais vu ce comportement), je ne pourrais pas agir dessus, désolé :-/ Auquel cas je te recommande un post sur le site de la communauté pour qu'un CM fasse remonter. Un dump de la console + une copie de l'élément qui pose problème (ctrl+Maj+C puis clic gauche sur la fenêtre à problème, puis bouton de droite => copy élément) sera également probablement bienvenu. (vaut mieux mettre sur le site de la communauté pour être sûr que des données sensibles ne fuitent pas).

Pour l'instant je ferme l'issue, mais si jamais tu penses qu'elle est liée à Weda-Helper, dis-le ici et je ré-ouvre

Merci :)

**Comment by Ttt131** [comment]
Ok merci je fais ça !
j'avais déjà mis un post sur la communauté mais bon ils mettent 6 mois à réagir en général, j'ai rajouté une capture avec la console
Je ne pense pas que ce soit Weda Helper, ça persiste avec les extensions désactivées
