### ISSUE TITLE
Unités valeurs de suivi : problème des espaces

### ISSUE THREAD

**Issue by tpuszkarek** [Refhi/Weda-Helper#76]
Bonjour,

Petit-pense bête suite à ta réponse sur le forum de Weda : pourrais-tu rendre l'utilisation d'unités compatible les valeurs de suivi contenant des espaces ?
J'ai vu la possibilité de passer par "règles de suivi" dans "applicatifs" mais je ne voudrais pas imputer toute la MSP :)

A nouveau, merci pour tout ce que tu fais !

**Comment by Refhi** [comment]
Après vérification en fait les espaces semblent fonctionner de mon côté.
Si tu ne vois pas d'unité apparaître pour une question par exemple nommée "Tension Artérielle", je t'invite à aller dans les options de Weda Helper et de compléter le champ de texte pour y ajouter tes préférences, par exemple d'ajouter Tension Artérielle Systolique:mmHg,Tension Artérielle Diastolique:mmHg etc.
Je ferme le ticket pour l'instant, tiens-moi au courant si tu es en difficulté :)
