### ISSUE TITLE
Affichage des antécédents en haut de la page de création d'une consultation

### ISSUE THREAD

**Issue by tpuszkarek** [Refhi/Weda-Helper#77]
Bonjour,

L'affichage des antécédents en haut de la page de création d'une consultation est vraiment agréable.

Après réflexion et un peu de pratique, je m'interroge sur la possibilité de définir un raccourci clavier pour l'afficher, plutôt que de l'afficher systématiquement : l'affichage est souvent utile, parfois non, et j'hypertrophie certainement les antécédents ce qui fait qu'il faut scroller pour aller au sein de la consultation.

Si c'est possible et si tu en trouves le temps, pourrais-tu peut-être laisser le choix de l'afficher systématiquement / non / ou sur un raccourci clavier ?

Merci encore pour cet immense travail !

**Comment by Refhi** [comment]
fait :)
ça sera dans la prochaine version (probablement 2.0 !)
