### ISSUE TITLE
Amélioration: Curseur directement dans le champ de recherche à l'ouverture du module de prescription.

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#78]
Pour gagner encore qq précieuses milli secondes!

**Comment by Refhi** [comment]
c'est Weda-Helper qui retire le focus au moment de l'ajout des boutons :'-(
 je travaille dessus

**Comment by Refhi** [comment]
ah zut. Je n'arrive pas à reproduire le bug sous chromium.
Peux-tu me confirmer le navigateur que tu utilises et me mettre une copie de la console stp ?
Peux-tu également me dire si le bug est systématique ou intermittent ?

Merci :)

**Comment by Refhi** [comment]
@DrFloW71 désolé pour la relance, mais as-tu pu ré-essayer ?

**Comment by DrFloW71** [comment]
Salut, je vois seulement ton message. Je ne sais pas pourquoi j'ai pas mal de messages de guithub qui n'arrivent pas dans la bonne boîte. Je teste ça lundi au boulot.

**Comment by DrFloW71** [comment]
Salut je ;4y suis enfin mis! Je confirme que le curseur n'est pas dans la textbox à l'ouverture des prescriptions.
Voici la console:
![image](https://github.com/Refhi/Weda-Helper/assets/157386513/9b4802eb-9d9a-458b-9b4a-0a03a161ceb5)

**Comment by Abeldvlpr** [comment]
Je pense que ca coince avec l'option "Ouvre automatiquement la fenêtre des ordonnances-types lors des prescriptions médicamenteuses"
Est-ce que le curseur se met au bon endroit si vous désactivez cette option ?

**Comment by Abeldvlpr** [comment]
Je vais regarder ca

**Comment by Refhi** [comment]
Je ferme car désormais suivi dans #109
