### ISSUE TITLE
Curseur dans la cadre titre lors de la création d'un nouvel ATCD

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#80]
Dans les antécédents, à la création d'un nouvel antécédent mettre le curseur dans la case Titre et non les détails comme actuellement. Ca n'a pas de sens mais c'est comme ça actuellement à priori...

**Comment by Refhi** [comment]
Fait pour la 2.1 (en option ou pas, je verrais plus tard)
