### ISSUE TITLE
Arrêt maladie sans carte vitale

### ISSUE THREAD

**Issue by DocDomi** [Refhi/Weda-Helper#81]
Suite à la mise à jour 2.0, j'ai un problème lorsque je veux faire un arrêt de travail sans carte vitale :

![image](https://github.com/Refhi/Weda-Helper/assets/34068412/c838e208-0495-4139-902c-e490936c5321)

Alors qu'auparavant, il proposait de faire cet arrêt de travail "manuellement" en reprenant simplement le NIR du patient.

**Comment by Refhi** [comment]
Je vois deux solutions potentielles :
- soit annuler la lecture auto de la carte vitale, et donc remettre ce choix avant la suite : 
![image](https://github.com/Refhi/Weda-Helper/assets/2778215/21a645dc-61b9-495a-a30d-c3c6ed66cb9b)
- soit rajouter une deuxième bouton à côté de "AT" qui s’appellerait "AT sans carte vitale"
![image](https://github.com/Refhi/Weda-Helper/assets/2778215/e270e68f-6139-41c2-9912-9b302068080f)
qu'en pensez-vous ?

**Comment by Refhi** [comment]
Du coup j'ai mis la 2e option : 
![image](https://github.com/Refhi/Weda-Helper/assets/2778215/34cfd324-df9d-4dc3-8af8-fb5bc891083d)
ce sera corrigé dans la 2.1

**Comment by DocDomi** [comment]
Désolé, je découvre vos messages aujourd'hui. 

La solution que vous avez choisie me convient tout à fait !
