### ISSUE TITLE
Impression AM

### ISSUE THREAD

**Issue by DrFloW71** [Refhi/Weda-Helper#82]
Lors de la création des AM sur Weda la fenêtre se ferme tout seule sans laisser le temps d'imprimer le double pour la patient. Serait il possible de lancer l'impression automatique en même temps?

**Comment by Refhi** [comment]
Mmm... semblerait que j'aie aussi le problème de mon côté, j'investigue.

**Comment by Refhi** [comment]
Normalement le problème a été résolu dans la 2.1

J'ai aussi rajouté un paramètre pour éviter les problèmes si le Companion est absent. (il ne ferme pas la fenêtre d'impression)
