### ISSUE TITLE
Amélioration: raccourci pour le tiers payant dans le module de facturation

### ISSUE THREAD

**Issue by seastienherve** [Refhi/Weda-Helper#84]
Merci pour cet excellent add-on.
Je facture très souvent en tiers payant et du coup je dois a chaque fois cliquer pour le tiers payant:
est ce possible techniquement un raccourci pour le tiers payant ?

Sébastien

**Comment by Refhi** [comment]
Jusqu'ici j'avais plutôt décliné ces demandes car il est possible de paramètrer ça directement dans pyxvital, mais vu le nombre de personnes le demandant, je met ça dans la todo-list

**Comment by seastienherve** [comment]
Merci beaucoup ;)

**Comment by Abeldvlpr** [comment]
Implémenté dans #91
