### ISSUE TITLE
telecharger

### ISSUE THREAD

**Issue by cltrt76** [Refhi/Weda-Helper#85]
Bonjour 
encore bravo et merci pour ce travail et ce gain de temps au quotidien 

je me demandais faisant bcp de téléconsultation et ayant besoin de télécharger l'ordonnance serait il possible de créer une raccourci comme pour l'impression ctrl + p mais pour télécharger le pdf avec en-tête (plutôt que le dernier chemin du code aille sur l'icone imprimante qu'il aille sur celui télécharger)  ?

**Comment by cltrt76** [comment]
> Bonjour encore bravo et merci pour ce travail et ce gain de temps au quotidien
> 
> je me demandais faisait bcp de téléconsultation et ayant besoin de télécharger l'ordonnance serait il possible de créer une raccourci comme pour l'impression ctrl + p mais pour télécharger le pdf avec en-tête (plutôt que le dernier chemin du code aille sur l'icone imprimante qu'il aille sur celui télécharger) ?



> Bonjour encore bravo et merci pour ce travail et ce gain de temps au quotidien
> 
> je me demandais faisait bcp de téléconsultation et ayant besoin de télécharger l'ordonnance serait il possible de créer une raccourci comme pour l'impression ctrl + p mais pour télécharger le pdf avec en-tête (plutôt que le dernier chemin du code aille sur l'icone imprimante qu'il aille sur celui télécharger) ?

**Comment by Refhi** [comment]
Je me permet de re ouvrir le ticket (fausse manip ?)

En tout cas oui c'est possible, j'imagine peut-être le coupler avec un système de signature 🤔

**Comment by Refhi** [comment]
Donc c'est implémenté dans la 2.2 grace à #97 (merci @Abeldvlpr )

@Abeldvlpr est-ce que tu aurais une idée pour intégrer directement la signature dans le pdf ?

J'imagine qu'on pourrait télécharger le blob, agir dessus (peut-être avec la lib que tu utilises  dans  pour y insérer la signature dans #105 ?) puis enfin le télécharger ?

**Comment by Abeldvlpr** [comment]
C'est possible oui mais ça implique pas mal de boulot pour détecter où placer la signature + ca demande que l'utilisateur fournisse sa signature à l'extension..
Ca me parait plus logique de passer par les modèles de documents de Weda qui intègrent une signature et de laisser le choix dans les réglages de l'extension du modèle utilisé lorsqu'on télécharge le document (en laissant par défaut le premier modèle de la liste).

**Comment by Refhi** [comment]
fait dans https://github.com/Refhi/Weda-Helper/commit/a1c7607ab2966be589733ac79d550721273635f0
=> l'impression concerne désormais le 1er modèle, et le téléchargement le second.
=> à voir comment on met ça dans les options ?

**Comment by Abeldvlpr** [comment]
Si ca te va je rajoute un sélecteur dans les options pour permettre de choisir le modèle utilisé pour chaque fonction.
Avec ton implémentation de `startPrinting` ca va être simple à mettre en place

**Comment by Refhi** [comment]
Bonne idée, j'attends ta PR
(on commence à avoir un ensemble plus facile à maintenir, c'est satisfaisant)

**Comment by Refhi** [comment]
désolé @Abeldvlpr, je m'en suis occupé en faisant la #88 :-/
