### ISSUE TITLE
Raccourcis clavier pour Document Joint et impression recto-verso par le Companion

### ISSUE THREAD

**Issue by ced-974** [Refhi/Weda-Helper#87]
-Raccourcis clavier pour Documents Joints: par exemple Alt+8

id="ButtonDocumentJointAction"

-Impression recto-verso par le Companion, actuellement il imprime en recto simple

Merci :-)

**Comment by Refhi** [comment]
Merci pour le ticket, je m'en occupe à l'occasion.

Pour l'impression recto verso c'est déjà possible, il faut simplement l'activer dans les paramètres d'impression par défaut dans Windows :)

**Comment by Refhi** [comment]
@ced-974 @Abeldvlpr a trouvé une autre solution : l'upload automatique du fichier le plus récent d'un dossier donné avec le raccourcis Ctrl+U (ça va être dans la 2.3 qu'on publie normalement semaine pro, associé au nouveau Companion que tu peux télécharger dès maintenant.

Ça ne répond pas _stricto sensu_ à ta demande, mais est-ce que ça répond à ton besoin ?

**Comment by ced-974** [comment]
Bonjour Abel,
Merci pour ton message, j'utilise très souvent la page 'Document Joint', donc le raccourci clavier me serait bien utile.
C'est une bonne chose l'upload automatique du fichier le + récent d'un répertoire par Ctrl+U
Merci.

**Comment by Refhi** [comment]
Top merci
Je clôture, tu n'as plus qu'à attendre la mise à jour :)
