### ISSUE TITLE
Gestion des imprimantes multiples à implémenter

### ISSUE THREAD

**Issue by Philout14** [Refhi/Weda-Helper#88]
Bonjour,
Concernant l'impression automatique : je ne suis pas sûr d'avoir bien compris comment l'utiliser : j'ai créé un raccourcis clavier dans les paramètres de l'extension dans Chrome, l'impression est bien déclenchée par le raccourcis clavier, mais comment la gérer lorsqu'il y a plusieurs types d'en-tête dynamique ? (j'ai des modèles en A4 monozones et bizones, en A5 sécurisé...).
Merci

**Comment by atommmy** [comment]
Bonjour,
Oui je suis dans le même cas que toi.. du coup je ne m'en sers que quand j'ai besoin d'imprimer avec mon modèle par défaut...

**Comment by DrFloW71** [comment]
Oui c'est le premier modèle qui sera imprimé. C'est le comportement normal. Pour les autres modèles il faut faire en manuel.

**Comment by Refhi** [comment]
Pas d'échanges depuis un bout, je pense que le sujet est clos ?

N'hésitez pas à me dire s'il faut qu'on relance la discussion.

**Comment by Philout14** [comment]
je n'avais pas grand chose à rajouter à ça... du coup, en renommant les modèles pour que cela permette d'utiliser un modèle "par défaut" serait une solution ?

**Comment by Refhi** [comment]
il faudrait qu'on ajoute la gestion des modèles multiples d'ordonnances, similaire à #85
Pour l'instant j'ai envoyé un message à notre expert pour savoir s'il est possible de modifier l'ordre des en-têtes sans passer par une modification de Weda-Helper

**Comment by Refhi** [comment]
=> apparemment il y  a une valeur dans les modèles qui s'appelle "ordre de tri", qui semble mettre en haut le modèle dont "ordre de tri" est le plus bas.

@Abeldvlpr en implémentant #85 on en profite pour rajouter des raccourcis claviers supplémentaires pour ces cas de figures annexe ? (genre ctrl+P = on imprime le 1er modèle, ctrl+T on télécharge via le second modèle, ctrl+F1 on imprime le modèle 3, ctrl+F2 le modèle 4, etc. en optionnel ?)
