### ISSUE TITLE
Cotation "Défaut"

### ISSUE THREAD

**Issue by Philout14** [Refhi/Weda-Helper#89]
Bonjour, j'ai beau mettre une cotation intitulée "Défaut", elle ne s'applique pas lors de la création de la FSE...

**Comment by Refhi** [comment]
@Philout14 Je n'ai pas reçu de réponse de ta part, du coup je cloture pour l'instant. N'hésite pas à répondre ici si tu souhaites qu'on ré-ouvre ou qu'on échange.

**Comment by Philout14** [comment]
Bonjour @Refhi  et @atommmy désolé pour le retard à vous répondre.
Effectivement ça fonctionne bien, je n'avais pas compris qu'il fallait nécessairement passer par l'usage de "o/n"... 
Merci de votre aide
