### ISSUE TITLE
Ajouter un raccourci pour uploader le dernier document d'un dossier dans le dossier patient

### ISSUE THREAD

**Issue by Abeldvlpr** [Refhi/Weda-Helper#98]
Ajouts dans le companion:
- Surveillance d'un dossier spécifié par l'utilisateur (typiquement un dossier de scan de documents)
- A la demande de l'extension, envoie un binary du dernier fichier pdf/jpeg ajouté ou modifié dans ce dossier directement à l'extension

Ajouts dans l'extension:
- Détection automatique du formulaire pour envoi d'un fichier dans le dossier patient actuel
- Envoie du binary envoyé par le companion en créant une requête POST sur le formulaire d'upload
- Ouverture automatique de la fênetre de modification du document pour permettre la saisie du type de document, spécialité, date, résumé etc. (optionnel)

**Comment by Refhi** [comment]
@Abeldvlpr  est-ce que tu as pu jeter un œil là-dessus ?

Sinon je demande à mon frère à l'occasion de m'aider à voir si on a une api ou équivalent où se greffer pour l'envoi direct.

**Comment by Abeldvlpr** [comment]
Oui j'ai trouvé l'URL utilisée pour l'upload, la question qui se pose est de savoir par quel moyen on transmet le fichier, sachant que l'extension ne peut pas accéder directement aux fichiers de l'utilisateur.
Le plus simple me semble être de rajouter un endpoint dans le companion qui renvoie le contenu du dernier fichier (avec des mesures de sécurité pour limiter ça à certains types de fichiers). L'extension appelle cet endpoint et fait elle même la requête d'upload.
